-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DMA24bUnit_mm2s_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    STR_video_out_TREADY : IN STD_LOGIC;
    mm_fifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    mm_fifo_empty_n : IN STD_LOGIC;
    mm_fifo_read : OUT STD_LOGIC;
    mm_fifo_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    mm_fifo_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    last_i : IN STD_LOGIC_VECTOR (8 downto 0);
    bound : IN STD_LOGIC_VECTOR (19 downto 0);
    STR_video_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    STR_video_out_TVALID : OUT STD_LOGIC;
    STR_video_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    STR_video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of DMA24bUnit_mm2s_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_pp0_stage9 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_pp0_stage10 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_pp0_stage11 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_pp0_stage12 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_pp0_stage13 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_pp0_stage14 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_pp0_stage15 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln38_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage15 : signal is "none";
    signal icmp_ln38_reg_758 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state16_pp0_stage15_iter0_grp14 : BOOLEAN;
    signal ap_block_pp0_stage15_subdone : BOOLEAN;
    signal mm_fifo_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7_grp6 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage12 : signal is "none";
    signal ap_block_pp0_stage12_grp11 : BOOLEAN;
    signal STR_video_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_grp2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_grp3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_grp4 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_grp5 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage8 : signal is "none";
    signal ap_block_pp0_stage8_grp7 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage9 : signal is "none";
    signal ap_block_pp0_stage9_grp8 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage10 : signal is "none";
    signal ap_block_pp0_stage10_grp9 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage11 : signal is "none";
    signal ap_block_pp0_stage11_grp10 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage13 : signal is "none";
    signal ap_block_pp0_stage13_grp12 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage14 : signal is "none";
    signal ap_block_pp0_stage14_grp13 : BOOLEAN;
    signal ap_block_pp0_stage15_grp14 : BOOLEAN;
    signal ap_block_pp0_stage0_grp15 : BOOLEAN;
    signal ap_block_pp0_stage1_grp16 : BOOLEAN;
    signal reg_347 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state3_pp0_stage2_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp1 : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage7_11001_grp6 : BOOLEAN;
    signal ap_block_state13_pp0_stage12_iter0_grp11 : BOOLEAN;
    signal ap_block_pp0_stage12_11001_grp11 : BOOLEAN;
    signal reg_351 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_355 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_359 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_363 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_367 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_371 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_379 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_383 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_387 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_391 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_395 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_207_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_399 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal i_2_reg_747 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal icmp_ln39_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_752 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal add_ln38_fu_438_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln38_reg_762 : STD_LOGIC_VECTOR (19 downto 0);
    signal j_load_reg_767 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln38_1_fu_447_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln38_1_reg_772 : STD_LOGIC_VECTOR (11 downto 0);
    signal video_elt_out_last_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal video_elt_out_last_reg_777 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_197_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_reg_782 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_144 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal i_3_fu_523_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal j_fu_148 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal select_ln38_1_fu_463_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal indvar_flatten_fu_152 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal video_elt_out_data_fu_481_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage2_01001_grp1 : BOOLEAN;
    signal video_elt_out_data_1_fu_543_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state4_pp0_stage3_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage3_01001_grp2 : BOOLEAN;
    signal video_elt_out_data_2_fu_554_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state5_pp0_stage4_iter0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage4_01001_grp3 : BOOLEAN;
    signal video_elt_out_data_3_fu_565_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state6_pp0_stage5_iter0_grp4 : BOOLEAN;
    signal ap_block_pp0_stage5_01001_grp4 : BOOLEAN;
    signal video_elt_out_data_4_fu_576_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state7_pp0_stage6_iter0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage6_01001_grp5 : BOOLEAN;
    signal video_elt_out_data_5_fu_591_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage7_01001_grp6 : BOOLEAN;
    signal video_elt_out_data_6_fu_602_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state9_pp0_stage8_iter0_grp7 : BOOLEAN;
    signal ap_block_pp0_stage8_01001_grp7 : BOOLEAN;
    signal video_elt_out_data_7_fu_613_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state10_pp0_stage9_iter0_grp8 : BOOLEAN;
    signal ap_block_pp0_stage9_01001_grp8 : BOOLEAN;
    signal video_elt_out_data_8_fu_624_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state11_pp0_stage10_iter0_grp9 : BOOLEAN;
    signal ap_block_pp0_stage10_01001_grp9 : BOOLEAN;
    signal video_elt_out_data_9_fu_635_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state12_pp0_stage11_iter0_grp10 : BOOLEAN;
    signal ap_block_pp0_stage11_01001_grp10 : BOOLEAN;
    signal video_elt_out_data_10_fu_650_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage12_01001_grp11 : BOOLEAN;
    signal video_elt_out_data_11_fu_661_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state14_pp0_stage13_iter0_grp12 : BOOLEAN;
    signal ap_block_pp0_stage13_01001_grp12 : BOOLEAN;
    signal video_elt_out_data_12_fu_671_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state15_pp0_stage14_iter0_grp13 : BOOLEAN;
    signal ap_block_pp0_stage14_01001_grp13 : BOOLEAN;
    signal video_elt_out_data_13_fu_682_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage15_01001_grp14 : BOOLEAN;
    signal video_elt_out_data_14_fu_693_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state17_pp0_stage0_iter1_grp15 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp15 : BOOLEAN;
    signal video_elt_out_data_15_fu_704_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage1_01001_grp16 : BOOLEAN;
    signal video_elt_out_user_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage5_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage6_11001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage8_11001_grp7 : BOOLEAN;
    signal ap_block_pp0_stage9_11001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage10_11001_grp9 : BOOLEAN;
    signal ap_block_pp0_stage11_11001_grp10 : BOOLEAN;
    signal ap_block_pp0_stage13_11001_grp12 : BOOLEAN;
    signal ap_block_pp0_stage14_11001_grp13 : BOOLEAN;
    signal ap_block_pp0_stage15_11001_grp14 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp15 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp16 : BOOLEAN;
    signal zext_ln39_fu_424_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln38_fu_453_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln38_fu_459_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln60_fu_477_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln51_fu_468_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_498_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln51_fu_492_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln_fu_508_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln61_fu_587_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln62_fu_646_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_block_pp0_stage9_subdone : BOOLEAN;
    signal ap_block_pp0_stage10_subdone : BOOLEAN;
    signal ap_block_pp0_stage11_subdone : BOOLEAN;
    signal ap_block_pp0_stage12_subdone : BOOLEAN;
    signal ap_block_pp0_stage13_subdone : BOOLEAN;
    signal ap_block_pp0_stage14_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component DMA24bUnit_mm2s_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component DMA24bUnit_mm2s_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage15_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_fu_144 <= ap_const_lv8_0;
            elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                i_fu_144 <= i_3_fu_523_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_fu_152 <= ap_const_lv20_0;
            elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                indvar_flatten_fu_152 <= add_ln38_reg_762;
            end if; 
        end if;
    end process;

    j_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_148 <= ap_const_lv12_0;
            elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                j_fu_148 <= select_ln38_1_fu_463_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln38_1_reg_772 <= add_ln38_1_fu_447_p2;
                i_2_reg_747 <= i_fu_144;
                icmp_ln39_reg_752 <= icmp_ln39_fu_428_p2;
                j_load_reg_767 <= j_fu_148;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln38_reg_762 <= add_ln38_fu_438_p2;
                icmp_ln38_reg_758 <= icmp_ln38_fu_433_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then
                reg_347 <= mm_fifo_dout(31 downto 24);
                reg_351 <= mm_fifo_dout(39 downto 32);
                reg_355 <= mm_fifo_dout(47 downto 40);
                reg_359 <= mm_fifo_dout(55 downto 48);
                reg_363 <= mm_fifo_dout(63 downto 56);
                reg_367 <= mm_fifo_dout(71 downto 64);
                reg_371 <= mm_fifo_dout(79 downto 72);
                reg_375 <= mm_fifo_dout(87 downto 80);
                reg_379 <= mm_fifo_dout(95 downto 88);
                reg_383 <= mm_fifo_dout(103 downto 96);
                reg_387 <= mm_fifo_dout(111 downto 104);
                reg_391 <= mm_fifo_dout(119 downto 112);
                reg_395 <= mm_fifo_dout(127 downto 120);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)))) then
                reg_399 <= mm_fifo_dout(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then
                tmp_31_reg_782 <= mm_fifo_dout(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                video_elt_out_last_reg_777 <= video_elt_out_last_fu_472_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter0_stage1, ap_block_pp0_stage15_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage2_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_block_pp0_stage8_subdone, ap_block_pp0_stage9_subdone, ap_block_pp0_stage10_subdone, ap_block_pp0_stage11_subdone, ap_block_pp0_stage12_subdone, ap_block_pp0_stage13_subdone, ap_block_pp0_stage14_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when ap_ST_fsm_pp0_stage9 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage9_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                end if;
            when ap_ST_fsm_pp0_stage10 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage10_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                end if;
            when ap_ST_fsm_pp0_stage11 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage11_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                end if;
            when ap_ST_fsm_pp0_stage12 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage12_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage13;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage12;
                end if;
            when ap_ST_fsm_pp0_stage13 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage13_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage14;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage13;
                end if;
            when ap_ST_fsm_pp0_stage14 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage14_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage14;
                end if;
            when ap_ST_fsm_pp0_stage15 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage15_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage15;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;

    STR_video_out_TDATA_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, icmp_ln38_reg_758, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage12, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage9, ap_CS_fsm_pp0_stage10, ap_CS_fsm_pp0_stage11, ap_CS_fsm_pp0_stage13, ap_CS_fsm_pp0_stage14, video_elt_out_data_fu_481_p4, ap_block_pp0_stage2_01001_grp1, video_elt_out_data_1_fu_543_p4, ap_block_pp0_stage3_01001_grp2, video_elt_out_data_2_fu_554_p4, ap_block_pp0_stage4_01001_grp3, video_elt_out_data_3_fu_565_p4, ap_block_pp0_stage5_01001_grp4, video_elt_out_data_4_fu_576_p4, ap_block_pp0_stage6_01001_grp5, video_elt_out_data_5_fu_591_p4, ap_block_pp0_stage7_01001_grp6, video_elt_out_data_6_fu_602_p4, ap_block_pp0_stage8_01001_grp7, video_elt_out_data_7_fu_613_p4, ap_block_pp0_stage9_01001_grp8, video_elt_out_data_8_fu_624_p4, ap_block_pp0_stage10_01001_grp9, video_elt_out_data_9_fu_635_p4, ap_block_pp0_stage11_01001_grp10, video_elt_out_data_10_fu_650_p4, ap_block_pp0_stage12_01001_grp11, video_elt_out_data_11_fu_661_p4, ap_block_pp0_stage13_01001_grp12, video_elt_out_data_12_fu_671_p4, ap_block_pp0_stage14_01001_grp13, video_elt_out_data_13_fu_682_p4, ap_block_pp0_stage15_01001_grp14, video_elt_out_data_14_fu_693_p4, ap_block_pp0_stage0_01001_grp15, video_elt_out_data_15_fu_704_p4, ap_block_pp0_stage1_01001_grp16)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            STR_video_out_TDATA <= video_elt_out_data_15_fu_704_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            STR_video_out_TDATA <= video_elt_out_data_14_fu_693_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_01001_grp14) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15))) then 
            STR_video_out_TDATA <= video_elt_out_data_13_fu_682_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_01001_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14))) then 
            STR_video_out_TDATA <= video_elt_out_data_12_fu_671_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_01001_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13))) then 
            STR_video_out_TDATA <= video_elt_out_data_11_fu_661_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_01001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12))) then 
            STR_video_out_TDATA <= video_elt_out_data_10_fu_650_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_01001_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11))) then 
            STR_video_out_TDATA <= video_elt_out_data_9_fu_635_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_01001_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10))) then 
            STR_video_out_TDATA <= video_elt_out_data_8_fu_624_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_01001_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9))) then 
            STR_video_out_TDATA <= video_elt_out_data_7_fu_613_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_01001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
            STR_video_out_TDATA <= video_elt_out_data_6_fu_602_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_01001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            STR_video_out_TDATA <= video_elt_out_data_5_fu_591_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_01001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            STR_video_out_TDATA <= video_elt_out_data_4_fu_576_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_01001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            STR_video_out_TDATA <= video_elt_out_data_3_fu_565_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_01001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            STR_video_out_TDATA <= video_elt_out_data_2_fu_554_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            STR_video_out_TDATA <= video_elt_out_data_1_fu_543_p4;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            STR_video_out_TDATA <= video_elt_out_data_fu_481_p4;
        else 
            STR_video_out_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    STR_video_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, STR_video_out_TREADY, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, icmp_ln38_reg_758, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp1, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_grp6, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage12_grp11, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_grp2, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_grp3, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_grp4, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_grp5, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_grp7, ap_CS_fsm_pp0_stage9, ap_block_pp0_stage9_grp8, ap_CS_fsm_pp0_stage10, ap_block_pp0_stage10_grp9, ap_CS_fsm_pp0_stage11, ap_block_pp0_stage11_grp10, ap_CS_fsm_pp0_stage13, ap_block_pp0_stage13_grp12, ap_CS_fsm_pp0_stage14, ap_block_pp0_stage14_grp13, ap_block_pp0_stage15_grp14, ap_block_pp0_stage0_grp15, ap_block_pp0_stage1_grp16)
    begin
        if ((((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_grp14) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg 
    = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp2) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            STR_video_out_TDATA_blk_n <= STR_video_out_TREADY;
        else 
            STR_video_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    STR_video_out_TKEEP <= ap_const_lv3_7;

    STR_video_out_TLAST_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, icmp_ln38_reg_758, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage12, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage9, ap_CS_fsm_pp0_stage10, ap_CS_fsm_pp0_stage11, ap_CS_fsm_pp0_stage13, ap_CS_fsm_pp0_stage14, video_elt_out_last_reg_777, ap_block_pp0_stage2_01001_grp1, ap_block_pp0_stage3_01001_grp2, ap_block_pp0_stage4_01001_grp3, ap_block_pp0_stage5_01001_grp4, ap_block_pp0_stage6_01001_grp5, ap_block_pp0_stage7_01001_grp6, ap_block_pp0_stage8_01001_grp7, ap_block_pp0_stage9_01001_grp8, ap_block_pp0_stage10_01001_grp9, ap_block_pp0_stage11_01001_grp10, ap_block_pp0_stage12_01001_grp11, ap_block_pp0_stage13_01001_grp12, ap_block_pp0_stage14_01001_grp13, ap_block_pp0_stage15_01001_grp14, ap_block_pp0_stage0_01001_grp15, ap_block_pp0_stage1_01001_grp16)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            STR_video_out_TLAST <= video_elt_out_last_reg_777;
        elsif ((((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_01001_grp14) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_01001_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_01001_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_01001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_01001_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11)) or ((icmp_ln38_reg_758 
    = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_01001_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_01001_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_01001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_01001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_01001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg 
    = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_01001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_01001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            STR_video_out_TLAST <= ap_const_lv1_0;
        else 
            STR_video_out_TLAST <= "X";
        end if; 
    end process;

    STR_video_out_TSTRB <= ap_const_lv3_7;

    STR_video_out_TUSER_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, icmp_ln38_reg_758, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage12, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage9, ap_CS_fsm_pp0_stage10, ap_CS_fsm_pp0_stage11, ap_CS_fsm_pp0_stage13, ap_CS_fsm_pp0_stage14, ap_block_pp0_stage2_01001_grp1, ap_block_pp0_stage3_01001_grp2, ap_block_pp0_stage4_01001_grp3, ap_block_pp0_stage5_01001_grp4, ap_block_pp0_stage6_01001_grp5, ap_block_pp0_stage7_01001_grp6, ap_block_pp0_stage8_01001_grp7, ap_block_pp0_stage9_01001_grp8, ap_block_pp0_stage10_01001_grp9, ap_block_pp0_stage11_01001_grp10, ap_block_pp0_stage12_01001_grp11, ap_block_pp0_stage13_01001_grp12, ap_block_pp0_stage14_01001_grp13, ap_block_pp0_stage15_01001_grp14, ap_block_pp0_stage0_01001_grp15, ap_block_pp0_stage1_01001_grp16, video_elt_out_user_fu_516_p2)
    begin
        if ((((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_01001_grp14) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_01001_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_01001_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_01001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_01001_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11)) or ((icmp_ln38_reg_758 
    = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_01001_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_01001_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_01001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_01001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_01001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg 
    = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_01001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_01001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            STR_video_out_TUSER <= ap_const_lv1_0;
        elsif (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            STR_video_out_TUSER <= video_elt_out_user_fu_516_p2;
        else 
            STR_video_out_TUSER <= "X";
        end if; 
    end process;


    STR_video_out_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, icmp_ln38_reg_758, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage12, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage8, ap_CS_fsm_pp0_stage9, ap_CS_fsm_pp0_stage10, ap_CS_fsm_pp0_stage11, ap_CS_fsm_pp0_stage13, ap_CS_fsm_pp0_stage14, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage7_11001_grp6, ap_block_pp0_stage12_11001_grp11, ap_block_pp0_stage3_11001_grp2, ap_block_pp0_stage4_11001_grp3, ap_block_pp0_stage5_11001_grp4, ap_block_pp0_stage6_11001_grp5, ap_block_pp0_stage8_11001_grp7, ap_block_pp0_stage9_11001_grp8, ap_block_pp0_stage10_11001_grp9, ap_block_pp0_stage11_11001_grp10, ap_block_pp0_stage13_11001_grp12, ap_block_pp0_stage14_11001_grp13, ap_block_pp0_stage15_11001_grp14, ap_block_pp0_stage0_11001_grp15, ap_block_pp0_stage1_11001_grp16)
    begin
        if ((((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp15) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_11001_grp14) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage14_11001_grp13) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage14)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage13_11001_grp12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage13)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_11001_grp10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11)) or ((icmp_ln38_reg_758 
    = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage10_11001_grp9) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage9_11001_grp8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage9)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_11001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg 
    = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            STR_video_out_TVALID <= ap_const_logic_1;
        else 
            STR_video_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    add_ln38_1_fu_447_p2 <= std_logic_vector(unsigned(j_fu_148) + unsigned(ap_const_lv12_1));
    add_ln38_fu_438_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_152) + unsigned(ap_const_lv20_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage10 <= ap_CS_fsm(10);
    ap_CS_fsm_pp0_stage11 <= ap_CS_fsm(11);
    ap_CS_fsm_pp0_stage12 <= ap_CS_fsm(12);
    ap_CS_fsm_pp0_stage13 <= ap_CS_fsm(13);
    ap_CS_fsm_pp0_stage14 <= ap_CS_fsm(14);
    ap_CS_fsm_pp0_stage15 <= ap_CS_fsm(15);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
    ap_CS_fsm_pp0_stage8 <= ap_CS_fsm(8);
    ap_CS_fsm_pp0_stage9 <= ap_CS_fsm(9);

    ap_block_pp0_stage0_01001_grp15_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state17_pp0_stage0_iter1_grp15)
    begin
                ap_block_pp0_stage0_01001_grp15 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage0_iter1_grp15));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp15_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state17_pp0_stage0_iter1_grp15)
    begin
                ap_block_pp0_stage0_11001_grp15 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage0_iter1_grp15));
    end process;

        ap_block_pp0_stage0_grp15 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state17_pp0_stage0_iter1_grp15)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_pp0_stage0_iter1_grp15));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage10_01001_grp9_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp9)
    begin
                ap_block_pp0_stage10_01001_grp9 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp9));
    end process;


    ap_block_pp0_stage10_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp9)
    begin
                ap_block_pp0_stage10_11001_grp9 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp9));
    end process;

        ap_block_pp0_stage10_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage10_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state11_pp0_stage10_iter0_grp9)
    begin
                ap_block_pp0_stage10_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage10_iter0_grp9));
    end process;


    ap_block_pp0_stage11_01001_grp10_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp10)
    begin
                ap_block_pp0_stage11_01001_grp10 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp10));
    end process;


    ap_block_pp0_stage11_11001_grp10_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp10)
    begin
                ap_block_pp0_stage11_11001_grp10 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp10));
    end process;

        ap_block_pp0_stage11_grp10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage11_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state12_pp0_stage11_iter0_grp10)
    begin
                ap_block_pp0_stage11_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage11_iter0_grp10));
    end process;


    ap_block_pp0_stage12_01001_grp11_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp11)
    begin
                ap_block_pp0_stage12_01001_grp11 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp11));
    end process;


    ap_block_pp0_stage12_11001_grp11_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp11)
    begin
                ap_block_pp0_stage12_11001_grp11 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp11));
    end process;

        ap_block_pp0_stage12_grp11 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage12_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state13_pp0_stage12_iter0_grp11)
    begin
                ap_block_pp0_stage12_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage12_iter0_grp11));
    end process;


    ap_block_pp0_stage13_01001_grp12_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp12)
    begin
                ap_block_pp0_stage13_01001_grp12 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp12));
    end process;


    ap_block_pp0_stage13_11001_grp12_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp12)
    begin
                ap_block_pp0_stage13_11001_grp12 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp12));
    end process;

        ap_block_pp0_stage13_grp12 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage13_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state14_pp0_stage13_iter0_grp12)
    begin
                ap_block_pp0_stage13_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage13_iter0_grp12));
    end process;


    ap_block_pp0_stage14_01001_grp13_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp13)
    begin
                ap_block_pp0_stage14_01001_grp13 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp13));
    end process;


    ap_block_pp0_stage14_11001_grp13_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp13)
    begin
                ap_block_pp0_stage14_11001_grp13 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp13));
    end process;

        ap_block_pp0_stage14_grp13 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage14_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state15_pp0_stage14_iter0_grp13)
    begin
                ap_block_pp0_stage14_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state15_pp0_stage14_iter0_grp13));
    end process;


    ap_block_pp0_stage15_01001_grp14_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp14)
    begin
                ap_block_pp0_stage15_01001_grp14 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp14));
    end process;


    ap_block_pp0_stage15_11001_grp14_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp14)
    begin
                ap_block_pp0_stage15_11001_grp14 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp14));
    end process;

        ap_block_pp0_stage15_grp14 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage15_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state16_pp0_stage15_iter0_grp14)
    begin
                ap_block_pp0_stage15_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state16_pp0_stage15_iter0_grp14));
    end process;


    ap_block_pp0_stage1_01001_grp16_assign_proc : process(ap_enable_reg_pp0_iter1, STR_video_out_TREADY)
    begin
                ap_block_pp0_stage1_01001_grp16 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, STR_video_out_TREADY)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp16_assign_proc : process(ap_enable_reg_pp0_iter1, STR_video_out_TREADY)
    begin
                ap_block_pp0_stage1_11001_grp16 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp16 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, STR_video_out_TREADY)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp1)
    begin
                ap_block_pp0_stage2_01001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp1));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp1)
    begin
                ap_block_pp0_stage2_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp1));
    end process;

        ap_block_pp0_stage2_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp1)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp1));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp2)
    begin
                ap_block_pp0_stage3_01001_grp2 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp2));
    end process;


    ap_block_pp0_stage3_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp2)
    begin
                ap_block_pp0_stage3_11001_grp2 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp2));
    end process;

        ap_block_pp0_stage3_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp2)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp2));
    end process;


    ap_block_pp0_stage4_01001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp3)
    begin
                ap_block_pp0_stage4_01001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp3));
    end process;


    ap_block_pp0_stage4_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp3)
    begin
                ap_block_pp0_stage4_11001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp3));
    end process;

        ap_block_pp0_stage4_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp3)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp3));
    end process;


    ap_block_pp0_stage5_01001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp4)
    begin
                ap_block_pp0_stage5_01001_grp4 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp4));
    end process;


    ap_block_pp0_stage5_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp4)
    begin
                ap_block_pp0_stage5_11001_grp4 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp4));
    end process;

        ap_block_pp0_stage5_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp4)
    begin
                ap_block_pp0_stage5_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp4));
    end process;


    ap_block_pp0_stage6_01001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp5)
    begin
                ap_block_pp0_stage6_01001_grp5 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp5));
    end process;


    ap_block_pp0_stage6_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp5)
    begin
                ap_block_pp0_stage6_11001_grp5 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp5));
    end process;

        ap_block_pp0_stage6_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp5)
    begin
                ap_block_pp0_stage6_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp5));
    end process;


    ap_block_pp0_stage7_01001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp6)
    begin
                ap_block_pp0_stage7_01001_grp6 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp6));
    end process;


    ap_block_pp0_stage7_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp6)
    begin
                ap_block_pp0_stage7_11001_grp6 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp6));
    end process;

        ap_block_pp0_stage7_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state8_pp0_stage7_iter0_grp6)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp6));
    end process;


    ap_block_pp0_stage8_01001_grp7_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp7)
    begin
                ap_block_pp0_stage8_01001_grp7 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp7));
    end process;


    ap_block_pp0_stage8_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp7)
    begin
                ap_block_pp0_stage8_11001_grp7 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp7));
    end process;

        ap_block_pp0_stage8_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage8_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state9_pp0_stage8_iter0_grp7)
    begin
                ap_block_pp0_stage8_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage8_iter0_grp7));
    end process;


    ap_block_pp0_stage9_01001_grp8_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp8)
    begin
                ap_block_pp0_stage9_01001_grp8 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp8));
    end process;


    ap_block_pp0_stage9_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp8)
    begin
                ap_block_pp0_stage9_11001_grp8 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp8));
    end process;

        ap_block_pp0_stage9_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage9_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state10_pp0_stage9_iter0_grp8)
    begin
                ap_block_pp0_stage9_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage9_iter0_grp8));
    end process;


    ap_block_state10_pp0_stage9_iter0_grp8_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state10_pp0_stage9_iter0_grp8 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state11_pp0_stage10_iter0_grp9_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state11_pp0_stage10_iter0_grp9 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state12_pp0_stage11_iter0_grp10_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state12_pp0_stage11_iter0_grp10 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state13_pp0_stage12_iter0_grp11_assign_proc : process(STR_video_out_TREADY, mm_fifo_empty_n, icmp_ln38_reg_758)
    begin
                ap_block_state13_pp0_stage12_iter0_grp11 <= (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (mm_fifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state14_pp0_stage13_iter0_grp12_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state14_pp0_stage13_iter0_grp12 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state15_pp0_stage14_iter0_grp13_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state15_pp0_stage14_iter0_grp13 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state16_pp0_stage15_iter0_grp14_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state16_pp0_stage15_iter0_grp14 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state17_pp0_stage0_iter1_grp15_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state17_pp0_stage0_iter1_grp15 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state3_pp0_stage2_iter0_grp1_assign_proc : process(STR_video_out_TREADY, mm_fifo_empty_n, icmp_ln38_reg_758)
    begin
                ap_block_state3_pp0_stage2_iter0_grp1 <= (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (mm_fifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state4_pp0_stage3_iter0_grp2_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state4_pp0_stage3_iter0_grp2 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state5_pp0_stage4_iter0_grp3_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state5_pp0_stage4_iter0_grp3 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state6_pp0_stage5_iter0_grp4_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state6_pp0_stage5_iter0_grp4 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state7_pp0_stage6_iter0_grp5_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state7_pp0_stage6_iter0_grp5 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_block_state8_pp0_stage7_iter0_grp6_assign_proc : process(STR_video_out_TREADY, mm_fifo_empty_n, icmp_ln38_reg_758)
    begin
                ap_block_state8_pp0_stage7_iter0_grp6 <= (((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (mm_fifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state9_pp0_stage8_iter0_grp7_assign_proc : process(STR_video_out_TREADY, icmp_ln38_reg_758)
    begin
                ap_block_state9_pp0_stage8_iter0_grp7 <= ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_const_logic_0 = STR_video_out_TREADY));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln38_fu_433_p2)
    begin
        if (((icmp_ln38_fu_433_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage15, ap_block_pp0_stage15_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage15_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage15))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_197_p4 <= mm_fifo_dout(15 downto 8);
    grp_fu_207_p4 <= mm_fifo_dout(23 downto 16);
    i_3_fu_523_p2 <= std_logic_vector(unsigned(select_ln38_fu_453_p3) + unsigned(ap_const_lv8_1));
    icmp_ln38_fu_433_p2 <= "1" when (indvar_flatten_fu_152 = bound) else "0";
    icmp_ln39_fu_428_p2 <= "1" when (signed(zext_ln39_fu_424_p1) > signed(last_i)) else "0";

    mm_fifo_blk_n_assign_proc : process(mm_fifo_empty_n, ap_enable_reg_pp0_iter0_reg, icmp_ln38_reg_758, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp1, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_grp6, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage12_grp11)
    begin
        if ((((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            mm_fifo_blk_n <= mm_fifo_empty_n;
        else 
            mm_fifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    mm_fifo_read_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln38_reg_758, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage12, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage7_11001_grp6, ap_block_pp0_stage12_11001_grp11)
    begin
        if ((((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage12_11001_grp11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage12)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((icmp_ln38_reg_758 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            mm_fifo_read <= ap_const_logic_1;
        else 
            mm_fifo_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln51_fu_492_p2 <= (trunc_ln51_fu_468_p1 or select_ln38_fu_453_p3);
    or_ln_fu_508_p3 <= (tmp_15_fu_498_p4 & or_ln51_fu_492_p2);
    select_ln38_1_fu_463_p3 <= 
        add_ln38_1_reg_772 when (icmp_ln39_reg_752(0) = '1') else 
        j_load_reg_767;
    select_ln38_fu_453_p3 <= 
        ap_const_lv8_0 when (icmp_ln39_reg_752(0) = '1') else 
        i_2_reg_747;
    tmp_15_fu_498_p4 <= select_ln38_1_fu_463_p3(11 downto 8);
    trunc_ln51_fu_468_p1 <= select_ln38_1_fu_463_p3(8 - 1 downto 0);
    trunc_ln60_fu_477_p1 <= mm_fifo_dout(8 - 1 downto 0);
    trunc_ln61_fu_587_p1 <= mm_fifo_dout(8 - 1 downto 0);
    trunc_ln62_fu_646_p1 <= mm_fifo_dout(8 - 1 downto 0);
    video_elt_out_data_10_fu_650_p4 <= ((reg_391 & reg_395) & trunc_ln62_fu_646_p1);
    video_elt_out_data_11_fu_661_p4 <= ((tmp_31_reg_782 & reg_399) & reg_347);
    video_elt_out_data_12_fu_671_p4 <= ((reg_351 & reg_355) & reg_359);
    video_elt_out_data_13_fu_682_p4 <= ((reg_363 & reg_367) & reg_371);
    video_elt_out_data_14_fu_693_p4 <= ((reg_375 & reg_379) & reg_383);
    video_elt_out_data_15_fu_704_p4 <= ((reg_387 & reg_391) & reg_395);
    video_elt_out_data_1_fu_543_p4 <= ((reg_347 & reg_351) & reg_355);
    video_elt_out_data_2_fu_554_p4 <= ((reg_359 & reg_363) & reg_367);
    video_elt_out_data_3_fu_565_p4 <= ((reg_371 & reg_375) & reg_379);
    video_elt_out_data_4_fu_576_p4 <= ((reg_383 & reg_387) & reg_391);
    video_elt_out_data_5_fu_591_p4 <= ((reg_395 & trunc_ln61_fu_587_p1) & grp_fu_197_p4);
    video_elt_out_data_6_fu_602_p4 <= ((reg_399 & reg_347) & reg_351);
    video_elt_out_data_7_fu_613_p4 <= ((reg_355 & reg_359) & reg_363);
    video_elt_out_data_8_fu_624_p4 <= ((reg_367 & reg_371) & reg_375);
    video_elt_out_data_9_fu_635_p4 <= ((reg_379 & reg_383) & reg_387);
    video_elt_out_data_fu_481_p4 <= ((trunc_ln60_fu_477_p1 & grp_fu_197_p4) & grp_fu_207_p4);
    video_elt_out_last_fu_472_p2 <= "1" when (zext_ln38_fu_459_p1 = last_i) else "0";
    video_elt_out_user_fu_516_p2 <= "1" when (or_ln_fu_508_p3 = ap_const_lv12_0) else "0";
    zext_ln38_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln38_fu_453_p3),9));
    zext_ln39_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_144),9));
end behav;
