-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DMA24bUnit_mm2s_DMA24b_mm2s is
port (
    STR_video_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    STR_video_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    STR_video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    image_w : IN STD_LOGIC_VECTOR (11 downto 0);
    image_h : IN STD_LOGIC_VECTOR (11 downto 0);
    m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    BAR_image_in : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    BAR_image_in_ap_vld : IN STD_LOGIC;
    image_w_ap_vld : IN STD_LOGIC;
    image_h_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    STR_video_out_TVALID : OUT STD_LOGIC;
    STR_video_out_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of DMA24bUnit_mm2s_DMA24b_mm2s is 
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal DMA24b_mm2s_fetch_U0_ap_start : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_done : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_continue : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_idle : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_ready : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_start_out : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_start_write : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_mm_fifo_din : STD_LOGIC_VECTOR (127 downto 0);
    signal DMA24b_mm2s_fetch_U0_mm_fifo_write : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_image_w_c_din : STD_LOGIC_VECTOR (11 downto 0);
    signal DMA24b_mm2s_fetch_U0_image_w_c_write : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_image_h_c_din : STD_LOGIC_VECTOR (11 downto 0);
    signal DMA24b_mm2s_fetch_U0_image_h_c_write : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_start : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_done : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_continue : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_idle : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_ready : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TVALID : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_streamout_U0_mm_fifo_read : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_img_w_read : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_img_h_read : STD_LOGIC;
    signal mm_fifo_full_n : STD_LOGIC;
    signal mm_fifo_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal mm_fifo_empty_n : STD_LOGIC;
    signal mm_fifo_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal mm_fifo_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal image_w_c_full_n : STD_LOGIC;
    signal image_w_c_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal image_w_c_empty_n : STD_LOGIC;
    signal image_w_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal image_w_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal image_h_c_full_n : STD_LOGIC;
    signal image_h_c_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal image_h_c_empty_n : STD_LOGIC;
    signal image_h_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal image_h_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal start_for_DMA24b_mm2s_streamout_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_DMA24b_mm2s_streamout_U0_full_n : STD_LOGIC;
    signal start_for_DMA24b_mm2s_streamout_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_DMA24b_mm2s_streamout_U0_empty_n : STD_LOGIC;

    component DMA24bUnit_mm2s_DMA24b_mm2s_fetch IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mm_buffer : IN STD_LOGIC_VECTOR (63 downto 0);
        mm_fifo_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        mm_fifo_full_n : IN STD_LOGIC;
        mm_fifo_write : OUT STD_LOGIC;
        mm_fifo_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        mm_fifo_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        img_w : IN STD_LOGIC_VECTOR (11 downto 0);
        img_h : IN STD_LOGIC_VECTOR (11 downto 0);
        image_w_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        image_w_c_full_n : IN STD_LOGIC;
        image_w_c_write : OUT STD_LOGIC;
        image_w_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        image_w_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        image_h_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
        image_h_c_full_n : IN STD_LOGIC;
        image_h_c_write : OUT STD_LOGIC;
        image_h_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        image_h_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component DMA24bUnit_mm2s_DMA24b_mm2s_streamout IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        STR_video_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        STR_video_out_TVALID : OUT STD_LOGIC;
        STR_video_out_TREADY : IN STD_LOGIC;
        STR_video_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        STR_video_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        STR_video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        STR_video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        mm_fifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        mm_fifo_empty_n : IN STD_LOGIC;
        mm_fifo_read : OUT STD_LOGIC;
        mm_fifo_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        mm_fifo_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        img_w_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        img_w_empty_n : IN STD_LOGIC;
        img_w_read : OUT STD_LOGIC;
        img_w_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_w_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_h_dout : IN STD_LOGIC_VECTOR (11 downto 0);
        img_h_empty_n : IN STD_LOGIC;
        img_h_read : OUT STD_LOGIC;
        img_h_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_h_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component DMA24bUnit_mm2s_fifo_w128_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component DMA24bUnit_mm2s_fifo_w12_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component DMA24bUnit_mm2s_start_for_DMA24b_mm2s_streamout_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    DMA24b_mm2s_fetch_U0 : component DMA24bUnit_mm2s_DMA24b_mm2s_fetch
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => DMA24b_mm2s_fetch_U0_ap_start,
        start_full_n => start_for_DMA24b_mm2s_streamout_U0_full_n,
        ap_done => DMA24b_mm2s_fetch_U0_ap_done,
        ap_continue => DMA24b_mm2s_fetch_U0_ap_continue,
        ap_idle => DMA24b_mm2s_fetch_U0_ap_idle,
        ap_ready => DMA24b_mm2s_fetch_U0_ap_ready,
        start_out => DMA24b_mm2s_fetch_U0_start_out,
        start_write => DMA24b_mm2s_fetch_U0_start_write,
        m_axi_gmem_0_AWVALID => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_0_AWADDR => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => ap_const_logic_0,
        m_axi_gmem_0_WDATA => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST => m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID => m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM => m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER => m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP => m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID => ap_const_logic_0,
        m_axi_gmem_0_BREADY => DMA24b_mm2s_fetch_U0_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_0_BID => ap_const_lv1_0,
        m_axi_gmem_0_BUSER => ap_const_lv1_0,
        mm_buffer => BAR_image_in,
        mm_fifo_din => DMA24b_mm2s_fetch_U0_mm_fifo_din,
        mm_fifo_full_n => mm_fifo_full_n,
        mm_fifo_write => DMA24b_mm2s_fetch_U0_mm_fifo_write,
        mm_fifo_num_data_valid => mm_fifo_num_data_valid,
        mm_fifo_fifo_cap => mm_fifo_fifo_cap,
        img_w => image_w,
        img_h => image_h,
        image_w_c_din => DMA24b_mm2s_fetch_U0_image_w_c_din,
        image_w_c_full_n => image_w_c_full_n,
        image_w_c_write => DMA24b_mm2s_fetch_U0_image_w_c_write,
        image_w_c_num_data_valid => image_w_c_num_data_valid,
        image_w_c_fifo_cap => image_w_c_fifo_cap,
        image_h_c_din => DMA24b_mm2s_fetch_U0_image_h_c_din,
        image_h_c_full_n => image_h_c_full_n,
        image_h_c_write => DMA24b_mm2s_fetch_U0_image_h_c_write,
        image_h_c_num_data_valid => image_h_c_num_data_valid,
        image_h_c_fifo_cap => image_h_c_fifo_cap);

    DMA24b_mm2s_streamout_U0 : component DMA24bUnit_mm2s_DMA24b_mm2s_streamout
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => DMA24b_mm2s_streamout_U0_ap_start,
        ap_done => DMA24b_mm2s_streamout_U0_ap_done,
        ap_continue => DMA24b_mm2s_streamout_U0_ap_continue,
        ap_idle => DMA24b_mm2s_streamout_U0_ap_idle,
        ap_ready => DMA24b_mm2s_streamout_U0_ap_ready,
        STR_video_out_TDATA => DMA24b_mm2s_streamout_U0_STR_video_out_TDATA,
        STR_video_out_TVALID => DMA24b_mm2s_streamout_U0_STR_video_out_TVALID,
        STR_video_out_TREADY => STR_video_out_TREADY,
        STR_video_out_TKEEP => DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP,
        STR_video_out_TSTRB => DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB,
        STR_video_out_TUSER => DMA24b_mm2s_streamout_U0_STR_video_out_TUSER,
        STR_video_out_TLAST => DMA24b_mm2s_streamout_U0_STR_video_out_TLAST,
        mm_fifo_dout => mm_fifo_dout,
        mm_fifo_empty_n => mm_fifo_empty_n,
        mm_fifo_read => DMA24b_mm2s_streamout_U0_mm_fifo_read,
        mm_fifo_num_data_valid => mm_fifo_num_data_valid,
        mm_fifo_fifo_cap => mm_fifo_fifo_cap,
        img_w_dout => image_w_c_dout,
        img_w_empty_n => image_w_c_empty_n,
        img_w_read => DMA24b_mm2s_streamout_U0_img_w_read,
        img_w_num_data_valid => image_w_c_num_data_valid,
        img_w_fifo_cap => image_w_c_fifo_cap,
        img_h_dout => image_h_c_dout,
        img_h_empty_n => image_h_c_empty_n,
        img_h_read => DMA24b_mm2s_streamout_U0_img_h_read,
        img_h_num_data_valid => image_h_c_num_data_valid,
        img_h_fifo_cap => image_h_c_fifo_cap);

    mm_fifo_U : component DMA24bUnit_mm2s_fifo_w128_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => DMA24b_mm2s_fetch_U0_mm_fifo_din,
        if_full_n => mm_fifo_full_n,
        if_write => DMA24b_mm2s_fetch_U0_mm_fifo_write,
        if_dout => mm_fifo_dout,
        if_empty_n => mm_fifo_empty_n,
        if_read => DMA24b_mm2s_streamout_U0_mm_fifo_read,
        if_num_data_valid => mm_fifo_num_data_valid,
        if_fifo_cap => mm_fifo_fifo_cap);

    image_w_c_U : component DMA24bUnit_mm2s_fifo_w12_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => DMA24b_mm2s_fetch_U0_image_w_c_din,
        if_full_n => image_w_c_full_n,
        if_write => DMA24b_mm2s_fetch_U0_image_w_c_write,
        if_dout => image_w_c_dout,
        if_empty_n => image_w_c_empty_n,
        if_read => DMA24b_mm2s_streamout_U0_img_w_read,
        if_num_data_valid => image_w_c_num_data_valid,
        if_fifo_cap => image_w_c_fifo_cap);

    image_h_c_U : component DMA24bUnit_mm2s_fifo_w12_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => DMA24b_mm2s_fetch_U0_image_h_c_din,
        if_full_n => image_h_c_full_n,
        if_write => DMA24b_mm2s_fetch_U0_image_h_c_write,
        if_dout => image_h_c_dout,
        if_empty_n => image_h_c_empty_n,
        if_read => DMA24b_mm2s_streamout_U0_img_h_read,
        if_num_data_valid => image_h_c_num_data_valid,
        if_fifo_cap => image_h_c_fifo_cap);

    start_for_DMA24b_mm2s_streamout_U0_U : component DMA24bUnit_mm2s_start_for_DMA24b_mm2s_streamout_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_DMA24b_mm2s_streamout_U0_din,
        if_full_n => start_for_DMA24b_mm2s_streamout_U0_full_n,
        if_write => DMA24b_mm2s_fetch_U0_start_write,
        if_dout => start_for_DMA24b_mm2s_streamout_U0_dout,
        if_empty_n => start_for_DMA24b_mm2s_streamout_U0_empty_n,
        if_read => DMA24b_mm2s_streamout_U0_ap_ready);




    DMA24b_mm2s_fetch_U0_ap_continue <= ap_const_logic_1;
    DMA24b_mm2s_fetch_U0_ap_start <= ap_start;
    DMA24b_mm2s_streamout_U0_ap_continue <= ap_continue;
    DMA24b_mm2s_streamout_U0_ap_start <= start_for_DMA24b_mm2s_streamout_U0_empty_n;
    STR_video_out_TDATA <= DMA24b_mm2s_streamout_U0_STR_video_out_TDATA;
    STR_video_out_TKEEP <= DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP;
    STR_video_out_TLAST <= DMA24b_mm2s_streamout_U0_STR_video_out_TLAST;
    STR_video_out_TSTRB <= DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB;
    STR_video_out_TUSER <= DMA24b_mm2s_streamout_U0_STR_video_out_TUSER;
    STR_video_out_TVALID <= DMA24b_mm2s_streamout_U0_STR_video_out_TVALID;
    ap_done <= DMA24b_mm2s_streamout_U0_ap_done;
    ap_idle <= (DMA24b_mm2s_streamout_U0_ap_idle and DMA24b_mm2s_fetch_U0_ap_idle);
    ap_ready <= DMA24b_mm2s_fetch_U0_ap_ready;
    m_axi_gmem_0_ARADDR <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARADDR;
    m_axi_gmem_0_ARBURST <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARBURST;
    m_axi_gmem_0_ARCACHE <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARCACHE;
    m_axi_gmem_0_ARID <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARID;
    m_axi_gmem_0_ARLEN <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLEN;
    m_axi_gmem_0_ARLOCK <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLOCK;
    m_axi_gmem_0_ARPROT <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARPROT;
    m_axi_gmem_0_ARQOS <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARQOS;
    m_axi_gmem_0_ARREGION <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARREGION;
    m_axi_gmem_0_ARSIZE <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARSIZE;
    m_axi_gmem_0_ARUSER <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARUSER;
    m_axi_gmem_0_ARVALID <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARVALID;
    m_axi_gmem_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_0_RREADY <= DMA24b_mm2s_fetch_U0_m_axi_gmem_0_RREADY;
    m_axi_gmem_0_WDATA <= ap_const_lv128_lc_1;
    m_axi_gmem_0_WID <= ap_const_lv1_0;
    m_axi_gmem_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_0_WSTRB <= ap_const_lv16_0;
    m_axi_gmem_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_0_WVALID <= ap_const_logic_0;
    start_for_DMA24b_mm2s_streamout_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
