-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DMA24bUnit_mm2s_DMA24b_mm2s_streamout is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    STR_video_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    STR_video_out_TVALID : OUT STD_LOGIC;
    STR_video_out_TREADY : IN STD_LOGIC;
    STR_video_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    STR_video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    mm_fifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    mm_fifo_empty_n : IN STD_LOGIC;
    mm_fifo_read : OUT STD_LOGIC;
    mm_fifo_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    mm_fifo_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    img_w_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    img_w_empty_n : IN STD_LOGIC;
    img_w_read : OUT STD_LOGIC;
    img_w_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_w_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    img_h_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    img_h_empty_n : IN STD_LOGIC;
    img_h_read : OUT STD_LOGIC;
    img_h_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_h_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of DMA24bUnit_mm2s_DMA24b_mm2s_streamout is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal img_w_blk_n : STD_LOGIC;
    signal img_h_blk_n : STD_LOGIC;
    signal img_h_1_reg_145 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tmp_s_reg_150 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal last_i_fu_138_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal last_i_reg_166 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_106_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal bound_reg_171 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start : STD_LOGIC;
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done : STD_LOGIC;
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_idle : STD_LOGIC;
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_ready : STD_LOGIC;
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TREADY : STD_LOGIC;
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_mm_fifo_read : STD_LOGIC;
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID : STD_LOGIC;
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal STR_video_out_TDATA_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal STR_video_out_TKEEP_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal STR_video_out_TSTRB_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal STR_video_out_TUSER_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal STR_video_out_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_106_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_106_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln37_fu_135_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal grp_fu_106_p00 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_106_p10 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component DMA24bUnit_mm2s_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        STR_video_out_TREADY : IN STD_LOGIC;
        mm_fifo_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        mm_fifo_empty_n : IN STD_LOGIC;
        mm_fifo_read : OUT STD_LOGIC;
        mm_fifo_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        mm_fifo_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        last_i : IN STD_LOGIC_VECTOR (8 downto 0);
        bound : IN STD_LOGIC_VECTOR (19 downto 0);
        STR_video_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        STR_video_out_TVALID : OUT STD_LOGIC;
        STR_video_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        STR_video_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        STR_video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        STR_video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component DMA24bUnit_mm2s_mul_12ns_8ns_20_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;



begin
    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72 : component DMA24bUnit_mm2s_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start,
        ap_done => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done,
        ap_idle => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_idle,
        ap_ready => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_ready,
        STR_video_out_TREADY => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TREADY,
        mm_fifo_dout => mm_fifo_dout,
        mm_fifo_empty_n => mm_fifo_empty_n,
        mm_fifo_read => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_mm_fifo_read,
        mm_fifo_num_data_valid => ap_const_lv9_0,
        mm_fifo_fifo_cap => ap_const_lv9_0,
        last_i => last_i_reg_166,
        bound => bound_reg_171,
        STR_video_out_TDATA => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA,
        STR_video_out_TVALID => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID,
        STR_video_out_TKEEP => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP,
        STR_video_out_TSTRB => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB,
        STR_video_out_TUSER => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER,
        STR_video_out_TLAST => grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST);

    mul_12ns_8ns_20_2_1_U26 : component DMA24bUnit_mm2s_mul_12ns_8ns_20_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 12,
        din1_WIDTH => 8,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_106_p0,
        din1 => grp_fu_106_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_106_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_ready = ap_const_logic_1)) then 
                    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID = ap_const_logic_1))) then
                STR_video_out_TDATA_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA;
                STR_video_out_TKEEP_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP;
                STR_video_out_TLAST_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST;
                STR_video_out_TSTRB_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB;
                STR_video_out_TUSER_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                bound_reg_171 <= grp_fu_106_p2;
                last_i_reg_166 <= last_i_fu_138_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                img_h_1_reg_145 <= img_h_dout;
                tmp_s_reg_150 <= img_w_dout(11 downto 4);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    STR_video_out_TDATA_assign_proc : process(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA, grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID, ap_CS_fsm_state4, STR_video_out_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID = ap_const_logic_1))) then 
            STR_video_out_TDATA <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA;
        else 
            STR_video_out_TDATA <= STR_video_out_TDATA_reg;
        end if; 
    end process;


    STR_video_out_TKEEP_assign_proc : process(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID, grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP, ap_CS_fsm_state4, STR_video_out_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID = ap_const_logic_1))) then 
            STR_video_out_TKEEP <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP;
        else 
            STR_video_out_TKEEP <= STR_video_out_TKEEP_reg;
        end if; 
    end process;


    STR_video_out_TLAST_assign_proc : process(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID, grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST, ap_CS_fsm_state4, STR_video_out_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID = ap_const_logic_1))) then 
            STR_video_out_TLAST <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST;
        else 
            STR_video_out_TLAST <= STR_video_out_TLAST_reg;
        end if; 
    end process;


    STR_video_out_TSTRB_assign_proc : process(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID, grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB, ap_CS_fsm_state4, STR_video_out_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID = ap_const_logic_1))) then 
            STR_video_out_TSTRB <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB;
        else 
            STR_video_out_TSTRB <= STR_video_out_TSTRB_reg;
        end if; 
    end process;


    STR_video_out_TUSER_assign_proc : process(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID, grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER, ap_CS_fsm_state4, STR_video_out_TUSER_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID = ap_const_logic_1))) then 
            STR_video_out_TUSER <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER;
        else 
            STR_video_out_TUSER <= STR_video_out_TUSER_reg;
        end if; 
    end process;

    STR_video_out_TVALID <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done)
    begin
        if ((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, img_w_empty_n, img_h_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (img_h_empty_n = ap_const_logic_0) or (img_w_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TREADY <= (ap_CS_fsm_state4 and STR_video_out_TREADY);
    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg;
    grp_fu_106_p0 <= grp_fu_106_p00(12 - 1 downto 0);
    grp_fu_106_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(img_h_1_reg_145),20));
    grp_fu_106_p1 <= grp_fu_106_p10(8 - 1 downto 0);
    grp_fu_106_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_150),20));

    img_h_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_h_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_h_blk_n <= img_h_empty_n;
        else 
            img_h_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_h_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_h_read <= ap_const_logic_1;
        else 
            img_h_read <= ap_const_logic_0;
        end if; 
    end process;


    img_w_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_w_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_w_blk_n <= img_w_empty_n;
        else 
            img_w_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_w_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_w_read <= ap_const_logic_1;
        else 
            img_w_read <= ap_const_logic_0;
        end if; 
    end process;

    last_i_fu_138_p2 <= std_logic_vector(unsigned(zext_ln37_fu_135_p1) + unsigned(ap_const_lv9_1FF));
    mm_fifo_read <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_mm_fifo_read;
    zext_ln37_fu_135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_150),9));
end behav;
