#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 25 17:10:39 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 3d8e28433fc74ad3860e0ce282d1c07c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot TPG_behav xil_defaultlib.TPG -log elaborate.log"
xelab -wto 3d8e28433fc74ad3860e0ce282d1c07c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot TPG_behav xil_defaultlib.TPG -log elaborate.log

