webtalk_init -webtalk_dir /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/IP/AXI4_stream_Slave/AXI4_stream_Slave.sim/sim_1/behav/xsim/xsim.dir/AXI4_stream_Slave_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep  4 18:07:12 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7d1a7d0f-81a8-45ee-88ca-bef436b74769" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7ad0c694514749c4acecbfb885fb0e7d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 24.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3088.510 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114936_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3977245557 -regid "" -xml /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/IP/AXI4_stream_Slave/AXI4_stream_Slave.sim/sim_1/behav/xsim/xsim.dir/AXI4_stream_Slave_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/IP/AXI4_stream_Slave/AXI4_stream_Slave.sim/sim_1/behav/xsim/xsim.dir/AXI4_stream_Slave_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/IP/AXI4_stream_Slave/AXI4_stream_Slave.sim/sim_1/behav/xsim/xsim.dir/AXI4_stream_Slave_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
