#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Sep 29 14:42:46 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 03adc44a21dd44d88aea10fbbf520b0b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot AXI_Select_behav xil_defaultlib.AXI_Select -log elaborate.log"
xelab -wto 03adc44a21dd44d88aea10fbbf520b0b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot AXI_Select_behav xil_defaultlib.AXI_Select -log elaborate.log

