#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 23 17:46:18 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 0dd6c3694caa457bab99dba0857662d0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot reset_wiz_tb_behav xil_defaultlib.reset_wiz_tb -log elaborate.log"
xelab -wto 0dd6c3694caa457bab99dba0857662d0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot reset_wiz_tb_behav xil_defaultlib.reset_wiz_tb -log elaborate.log

