// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module DMA24bUnit_mm2s_DMA24b_mm2s_fetch (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        mm_buffer,
        mm_fifo_din,
        mm_fifo_full_n,
        mm_fifo_write,
        mm_fifo_num_data_valid,
        mm_fifo_fifo_cap,
        img_w,
        img_h,
        image_w_c_din,
        image_w_c_full_n,
        image_w_c_write,
        image_w_c_num_data_valid,
        image_w_c_fifo_cap,
        image_h_c_din,
        image_h_c_full_n,
        image_h_c_write,
        image_h_c_num_data_valid,
        image_h_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [127:0] m_axi_gmem_0_WDATA;
output  [15:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [127:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [10:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [63:0] mm_buffer;
output  [127:0] mm_fifo_din;
input   mm_fifo_full_n;
output   mm_fifo_write;
input  [8:0] mm_fifo_num_data_valid;
input  [8:0] mm_fifo_fifo_cap;
input  [11:0] img_w;
input  [11:0] img_h;
output  [11:0] image_w_c_din;
input   image_w_c_full_n;
output   image_w_c_write;
input  [2:0] image_w_c_num_data_valid;
input  [2:0] image_w_c_fifo_cap;
output  [11:0] image_h_c_din;
input   image_h_c_full_n;
output   image_h_c_write;
input  [2:0] image_h_c_num_data_valid;
input  [2:0] image_h_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg image_w_c_write;
reg image_h_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    image_w_c_blk_n;
reg    image_h_c_blk_n;
reg   [11:0] img_h_read_reg_254;
reg    ap_block_state1;
wire   [9:0] beats_per_line_fu_151_p2;
reg   [9:0] beats_per_line_reg_259;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp32_fu_166_p2;
reg   [0:0] cmp32_reg_270;
reg   [4:0] tmp_1_reg_275;
wire    ap_CS_fsm_state3;
wire   [9:0] empty_fu_217_p3;
reg   [9:0] empty_reg_281;
wire    ap_CS_fsm_state4;
wire   [10:0] bound_fu_232_p2;
reg   [10:0] bound_reg_286;
wire   [9:0] empty_56_fu_238_p1;
reg   [9:0] empty_56_reg_291;
wire    ap_CS_fsm_state5;
wire   [21:0] grp_fu_248_p2;
reg   [21:0] bound4_reg_306;
wire    ap_CS_fsm_state6;
reg   [63:0] mm_buffer_read_reg_311;
wire    ap_CS_fsm_state7;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_done;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_idle;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_ready;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWID;
wire   [31:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWUSER;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WVALID;
wire   [127:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WDATA;
wire   [15:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WSTRB;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WLAST;
wire   [0:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WID;
wire   [0:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WUSER;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARID;
wire   [31:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARUSER;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_RREADY;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_BREADY;
wire   [127:0] grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_mm_fifo_din;
wire    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_mm_fifo_write;
reg    grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start_reg;
wire    ap_CS_fsm_state8;
wire   [7:0] tmp_fu_129_p4;
wire   [9:0] p_shl_fu_143_p3;
wire   [9:0] zext_ln12_fu_139_p1;
wire   [9:0] grp_fu_160_p0;
wire   [11:0] grp_fu_160_p1;
wire   [20:0] grp_fu_160_p2;
wire   [7:0] tmp_2_fu_200_p3;
wire   [9:0] p_shl1_fu_193_p3;
wire   [9:0] p_shl38_fu_207_p1;
wire   [9:0] mul_ln14_fu_211_p2;
wire   [10:0] p_shl35_fu_224_p1;
wire   [10:0] p_shl36_fu_228_p1;
wire   [11:0] grp_fu_248_p0;
wire   [10:0] grp_fu_248_p1;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire   [20:0] grp_fu_160_p00;
wire   [21:0] grp_fu_248_p00;
wire   [21:0] grp_fu_248_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start_reg = 1'b0;
end

DMA24bUnit_mm2s_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start),
    .ap_done(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_done),
    .ap_idle(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_idle),
    .ap_ready(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(m_axi_gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(m_axi_gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(m_axi_gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(m_axi_gmem_0_RLAST),
    .m_axi_gmem_0_RID(m_axi_gmem_0_RID),
    .m_axi_gmem_0_RFIFONUM(m_axi_gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(m_axi_gmem_0_RUSER),
    .m_axi_gmem_0_RRESP(m_axi_gmem_0_RRESP),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .mm_fifo_din(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_mm_fifo_din),
    .mm_fifo_full_n(mm_fifo_full_n),
    .mm_fifo_write(grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_mm_fifo_write),
    .mm_fifo_num_data_valid(9'd0),
    .mm_fifo_fifo_cap(9'd0),
    .bound4(bound4_reg_306),
    .p_cast(empty_reg_281),
    .bound(empty_56_reg_291),
    .mm_buffer(mm_buffer_read_reg_311)
);

DMA24bUnit_mm2s_mul_10ns_12ns_21_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
mul_10ns_12ns_21_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_160_p0),
    .din1(grp_fu_160_p1),
    .ce(1'b1),
    .dout(grp_fu_160_p2)
);

DMA24bUnit_mm2s_mul_12ns_11ns_22_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
mul_12ns_11ns_22_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_248_p0),
    .din1(grp_fu_248_p1),
    .ce(1'b1),
    .dout(grp_fu_248_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state8) & (grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_ready == 1'b1)) begin
            grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        beats_per_line_reg_259 <= beats_per_line_fu_151_p2;
        img_h_read_reg_254 <= img_h;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bound4_reg_306 <= grp_fu_248_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bound_reg_286[10 : 3] <= bound_fu_232_p2[10 : 3];
        empty_56_reg_291[9 : 3] <= empty_56_fu_238_p1[9 : 3];
        empty_reg_281[9 : 3] <= empty_fu_217_p3[9 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp32_reg_270 <= cmp32_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mm_buffer_read_reg_311 <= mm_buffer;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_1_reg_275 <= {{grp_fu_160_p2[20:16]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        image_h_c_blk_n = image_h_c_full_n;
    end else begin
        image_h_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        image_h_c_write = 1'b1;
    end else begin
        image_h_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        image_w_c_blk_n = image_w_c_full_n;
    end else begin
        image_w_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        image_w_c_write = 1'b1;
    end else begin
        image_w_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (image_h_c_full_n == 1'b0) | (image_w_c_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign beats_per_line_fu_151_p2 = (p_shl_fu_143_p3 - zext_ln12_fu_139_p1);

assign bound_fu_232_p2 = (p_shl35_fu_224_p1 + p_shl36_fu_228_p1);

assign cmp32_fu_166_p2 = ((beats_per_line_reg_259 > 10'd39) ? 1'b1 : 1'b0);

assign empty_56_fu_238_p1 = bound_fu_232_p2[9:0];

assign empty_fu_217_p3 = ((cmp32_reg_270[0:0] == 1'b1) ? mul_ln14_fu_211_p2 : 10'd0);

assign grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_ap_start_reg;

assign grp_fu_160_p0 = grp_fu_160_p00;

assign grp_fu_160_p00 = beats_per_line_reg_259;

assign grp_fu_160_p1 = 21'd1639;

assign grp_fu_248_p0 = grp_fu_248_p00;

assign grp_fu_248_p00 = img_h_read_reg_254;

assign grp_fu_248_p1 = grp_fu_248_p10;

assign grp_fu_248_p10 = bound_reg_286;

assign image_h_c_din = img_h;

assign image_w_c_din = img_w;

assign m_axi_gmem_0_ARADDR = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARADDR;

assign m_axi_gmem_0_ARBURST = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARBURST;

assign m_axi_gmem_0_ARCACHE = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARCACHE;

assign m_axi_gmem_0_ARID = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARID;

assign m_axi_gmem_0_ARLEN = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARLEN;

assign m_axi_gmem_0_ARLOCK = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARLOCK;

assign m_axi_gmem_0_ARPROT = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARPROT;

assign m_axi_gmem_0_ARQOS = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARQOS;

assign m_axi_gmem_0_ARREGION = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARREGION;

assign m_axi_gmem_0_ARSIZE = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARSIZE;

assign m_axi_gmem_0_ARUSER = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARUSER;

assign m_axi_gmem_0_ARVALID = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_ARVALID;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_RREADY = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_m_axi_gmem_0_RREADY;

assign m_axi_gmem_0_WDATA = 128'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 16'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign mm_fifo_din = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_mm_fifo_din;

assign mm_fifo_write = grp_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop_fu_116_mm_fifo_write;

assign mul_ln14_fu_211_p2 = (p_shl1_fu_193_p3 + p_shl38_fu_207_p1);

assign p_shl1_fu_193_p3 = {{tmp_1_reg_275}, {5'd0}};

assign p_shl35_fu_224_p1 = p_shl1_fu_193_p3;

assign p_shl36_fu_228_p1 = tmp_2_fu_200_p3;

assign p_shl38_fu_207_p1 = tmp_2_fu_200_p3;

assign p_shl_fu_143_p3 = {{tmp_fu_129_p4}, {2'd0}};

assign start_out = real_start;

assign tmp_2_fu_200_p3 = {{tmp_1_reg_275}, {3'd0}};

assign tmp_fu_129_p4 = {{img_w[11:4]}};

assign zext_ln12_fu_139_p1 = tmp_fu_129_p4;

always @ (posedge ap_clk) begin
    empty_reg_281[2:0] <= 3'b000;
    bound_reg_286[2:0] <= 3'b000;
    empty_56_reg_291[2:0] <= 3'b000;
end

endmodule //DMA24bUnit_mm2s_DMA24b_mm2s_fetch
