// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module DMA24bUnit_mm2s_DMA24b_mm2s (
        STR_video_out_TDATA,
        STR_video_out_TKEEP,
        STR_video_out_TSTRB,
        STR_video_out_TUSER,
        STR_video_out_TLAST,
        image_w,
        image_h,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        BAR_image_in,
        ap_clk,
        ap_rst,
        BAR_image_in_ap_vld,
        image_w_ap_vld,
        image_h_ap_vld,
        ap_start,
        STR_video_out_TVALID,
        STR_video_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [23:0] STR_video_out_TDATA;
output  [2:0] STR_video_out_TKEEP;
output  [2:0] STR_video_out_TSTRB;
output  [0:0] STR_video_out_TUSER;
output  [0:0] STR_video_out_TLAST;
input  [11:0] image_w;
input  [11:0] image_h;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [127:0] m_axi_gmem_0_WDATA;
output  [15:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [127:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [10:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [63:0] BAR_image_in;
input   ap_clk;
input   ap_rst;
input   BAR_image_in_ap_vld;
input   image_w_ap_vld;
input   image_h_ap_vld;
input   ap_start;
output   STR_video_out_TVALID;
input   STR_video_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    DMA24b_mm2s_fetch_U0_ap_start;
wire    DMA24b_mm2s_fetch_U0_ap_done;
wire    DMA24b_mm2s_fetch_U0_ap_continue;
wire    DMA24b_mm2s_fetch_U0_ap_idle;
wire    DMA24b_mm2s_fetch_U0_ap_ready;
wire    DMA24b_mm2s_fetch_U0_start_out;
wire    DMA24b_mm2s_fetch_U0_start_write;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWVALID;
wire   [63:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWADDR;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWID;
wire   [31:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLEN;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWSIZE;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWBURST;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLOCK;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWCACHE;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWPROT;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWQOS;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWREGION;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWUSER;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WVALID;
wire   [127:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WDATA;
wire   [15:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WSTRB;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WLAST;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WID;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WUSER;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARVALID;
wire   [63:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARADDR;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARID;
wire   [31:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLEN;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARSIZE;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARBURST;
wire   [1:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLOCK;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARCACHE;
wire   [2:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARPROT;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARQOS;
wire   [3:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARREGION;
wire   [0:0] DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARUSER;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_0_RREADY;
wire    DMA24b_mm2s_fetch_U0_m_axi_gmem_0_BREADY;
wire   [127:0] DMA24b_mm2s_fetch_U0_mm_fifo_din;
wire    DMA24b_mm2s_fetch_U0_mm_fifo_write;
wire   [11:0] DMA24b_mm2s_fetch_U0_image_w_c_din;
wire    DMA24b_mm2s_fetch_U0_image_w_c_write;
wire   [11:0] DMA24b_mm2s_fetch_U0_image_h_c_din;
wire    DMA24b_mm2s_fetch_U0_image_h_c_write;
wire    DMA24b_mm2s_streamout_U0_ap_start;
wire    DMA24b_mm2s_streamout_U0_ap_done;
wire    DMA24b_mm2s_streamout_U0_ap_continue;
wire    DMA24b_mm2s_streamout_U0_ap_idle;
wire    DMA24b_mm2s_streamout_U0_ap_ready;
wire   [23:0] DMA24b_mm2s_streamout_U0_STR_video_out_TDATA;
wire    DMA24b_mm2s_streamout_U0_STR_video_out_TVALID;
wire   [2:0] DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP;
wire   [2:0] DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB;
wire   [0:0] DMA24b_mm2s_streamout_U0_STR_video_out_TUSER;
wire   [0:0] DMA24b_mm2s_streamout_U0_STR_video_out_TLAST;
wire    DMA24b_mm2s_streamout_U0_mm_fifo_read;
wire    DMA24b_mm2s_streamout_U0_img_w_read;
wire    DMA24b_mm2s_streamout_U0_img_h_read;
wire    mm_fifo_full_n;
wire   [127:0] mm_fifo_dout;
wire    mm_fifo_empty_n;
wire   [8:0] mm_fifo_num_data_valid;
wire   [8:0] mm_fifo_fifo_cap;
wire    image_w_c_full_n;
wire   [11:0] image_w_c_dout;
wire    image_w_c_empty_n;
wire   [2:0] image_w_c_num_data_valid;
wire   [2:0] image_w_c_fifo_cap;
wire    image_h_c_full_n;
wire   [11:0] image_h_c_dout;
wire    image_h_c_empty_n;
wire   [2:0] image_h_c_num_data_valid;
wire   [2:0] image_h_c_fifo_cap;
wire   [0:0] start_for_DMA24b_mm2s_streamout_U0_din;
wire    start_for_DMA24b_mm2s_streamout_U0_full_n;
wire   [0:0] start_for_DMA24b_mm2s_streamout_U0_dout;
wire    start_for_DMA24b_mm2s_streamout_U0_empty_n;

DMA24bUnit_mm2s_DMA24b_mm2s_fetch DMA24b_mm2s_fetch_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DMA24b_mm2s_fetch_U0_ap_start),
    .start_full_n(start_for_DMA24b_mm2s_streamout_U0_full_n),
    .ap_done(DMA24b_mm2s_fetch_U0_ap_done),
    .ap_continue(DMA24b_mm2s_fetch_U0_ap_continue),
    .ap_idle(DMA24b_mm2s_fetch_U0_ap_idle),
    .ap_ready(DMA24b_mm2s_fetch_U0_ap_ready),
    .start_out(DMA24b_mm2s_fetch_U0_start_out),
    .start_write(DMA24b_mm2s_fetch_U0_start_write),
    .m_axi_gmem_0_AWVALID(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(m_axi_gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(m_axi_gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(m_axi_gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(m_axi_gmem_0_RLAST),
    .m_axi_gmem_0_RID(m_axi_gmem_0_RID),
    .m_axi_gmem_0_RFIFONUM(m_axi_gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(m_axi_gmem_0_RUSER),
    .m_axi_gmem_0_RRESP(m_axi_gmem_0_RRESP),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(DMA24b_mm2s_fetch_U0_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .mm_buffer(BAR_image_in),
    .mm_fifo_din(DMA24b_mm2s_fetch_U0_mm_fifo_din),
    .mm_fifo_full_n(mm_fifo_full_n),
    .mm_fifo_write(DMA24b_mm2s_fetch_U0_mm_fifo_write),
    .mm_fifo_num_data_valid(mm_fifo_num_data_valid),
    .mm_fifo_fifo_cap(mm_fifo_fifo_cap),
    .img_w(image_w),
    .img_h(image_h),
    .image_w_c_din(DMA24b_mm2s_fetch_U0_image_w_c_din),
    .image_w_c_full_n(image_w_c_full_n),
    .image_w_c_write(DMA24b_mm2s_fetch_U0_image_w_c_write),
    .image_w_c_num_data_valid(image_w_c_num_data_valid),
    .image_w_c_fifo_cap(image_w_c_fifo_cap),
    .image_h_c_din(DMA24b_mm2s_fetch_U0_image_h_c_din),
    .image_h_c_full_n(image_h_c_full_n),
    .image_h_c_write(DMA24b_mm2s_fetch_U0_image_h_c_write),
    .image_h_c_num_data_valid(image_h_c_num_data_valid),
    .image_h_c_fifo_cap(image_h_c_fifo_cap)
);

DMA24bUnit_mm2s_DMA24b_mm2s_streamout DMA24b_mm2s_streamout_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DMA24b_mm2s_streamout_U0_ap_start),
    .ap_done(DMA24b_mm2s_streamout_U0_ap_done),
    .ap_continue(DMA24b_mm2s_streamout_U0_ap_continue),
    .ap_idle(DMA24b_mm2s_streamout_U0_ap_idle),
    .ap_ready(DMA24b_mm2s_streamout_U0_ap_ready),
    .STR_video_out_TDATA(DMA24b_mm2s_streamout_U0_STR_video_out_TDATA),
    .STR_video_out_TVALID(DMA24b_mm2s_streamout_U0_STR_video_out_TVALID),
    .STR_video_out_TREADY(STR_video_out_TREADY),
    .STR_video_out_TKEEP(DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP),
    .STR_video_out_TSTRB(DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB),
    .STR_video_out_TUSER(DMA24b_mm2s_streamout_U0_STR_video_out_TUSER),
    .STR_video_out_TLAST(DMA24b_mm2s_streamout_U0_STR_video_out_TLAST),
    .mm_fifo_dout(mm_fifo_dout),
    .mm_fifo_empty_n(mm_fifo_empty_n),
    .mm_fifo_read(DMA24b_mm2s_streamout_U0_mm_fifo_read),
    .mm_fifo_num_data_valid(mm_fifo_num_data_valid),
    .mm_fifo_fifo_cap(mm_fifo_fifo_cap),
    .img_w_dout(image_w_c_dout),
    .img_w_empty_n(image_w_c_empty_n),
    .img_w_read(DMA24b_mm2s_streamout_U0_img_w_read),
    .img_w_num_data_valid(image_w_c_num_data_valid),
    .img_w_fifo_cap(image_w_c_fifo_cap),
    .img_h_dout(image_h_c_dout),
    .img_h_empty_n(image_h_c_empty_n),
    .img_h_read(DMA24b_mm2s_streamout_U0_img_h_read),
    .img_h_num_data_valid(image_h_c_num_data_valid),
    .img_h_fifo_cap(image_h_c_fifo_cap)
);

DMA24bUnit_mm2s_fifo_w128_d256_A mm_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DMA24b_mm2s_fetch_U0_mm_fifo_din),
    .if_full_n(mm_fifo_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_mm_fifo_write),
    .if_dout(mm_fifo_dout),
    .if_empty_n(mm_fifo_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_mm_fifo_read),
    .if_num_data_valid(mm_fifo_num_data_valid),
    .if_fifo_cap(mm_fifo_fifo_cap)
);

DMA24bUnit_mm2s_fifo_w12_d2_S image_w_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DMA24b_mm2s_fetch_U0_image_w_c_din),
    .if_full_n(image_w_c_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_image_w_c_write),
    .if_dout(image_w_c_dout),
    .if_empty_n(image_w_c_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_img_w_read),
    .if_num_data_valid(image_w_c_num_data_valid),
    .if_fifo_cap(image_w_c_fifo_cap)
);

DMA24bUnit_mm2s_fifo_w12_d2_S image_h_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DMA24b_mm2s_fetch_U0_image_h_c_din),
    .if_full_n(image_h_c_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_image_h_c_write),
    .if_dout(image_h_c_dout),
    .if_empty_n(image_h_c_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_img_h_read),
    .if_num_data_valid(image_h_c_num_data_valid),
    .if_fifo_cap(image_h_c_fifo_cap)
);

DMA24bUnit_mm2s_start_for_DMA24b_mm2s_streamout_U0 start_for_DMA24b_mm2s_streamout_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_DMA24b_mm2s_streamout_U0_din),
    .if_full_n(start_for_DMA24b_mm2s_streamout_U0_full_n),
    .if_write(DMA24b_mm2s_fetch_U0_start_write),
    .if_dout(start_for_DMA24b_mm2s_streamout_U0_dout),
    .if_empty_n(start_for_DMA24b_mm2s_streamout_U0_empty_n),
    .if_read(DMA24b_mm2s_streamout_U0_ap_ready)
);

assign DMA24b_mm2s_fetch_U0_ap_continue = 1'b1;

assign DMA24b_mm2s_fetch_U0_ap_start = ap_start;

assign DMA24b_mm2s_streamout_U0_ap_continue = ap_continue;

assign DMA24b_mm2s_streamout_U0_ap_start = start_for_DMA24b_mm2s_streamout_U0_empty_n;

assign STR_video_out_TDATA = DMA24b_mm2s_streamout_U0_STR_video_out_TDATA;

assign STR_video_out_TKEEP = DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP;

assign STR_video_out_TLAST = DMA24b_mm2s_streamout_U0_STR_video_out_TLAST;

assign STR_video_out_TSTRB = DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB;

assign STR_video_out_TUSER = DMA24b_mm2s_streamout_U0_STR_video_out_TUSER;

assign STR_video_out_TVALID = DMA24b_mm2s_streamout_U0_STR_video_out_TVALID;

assign ap_done = DMA24b_mm2s_streamout_U0_ap_done;

assign ap_idle = (DMA24b_mm2s_streamout_U0_ap_idle & DMA24b_mm2s_fetch_U0_ap_idle);

assign ap_ready = DMA24b_mm2s_fetch_U0_ap_ready;

assign m_axi_gmem_0_ARADDR = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARADDR;

assign m_axi_gmem_0_ARBURST = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARBURST;

assign m_axi_gmem_0_ARCACHE = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARCACHE;

assign m_axi_gmem_0_ARID = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARID;

assign m_axi_gmem_0_ARLEN = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLEN;

assign m_axi_gmem_0_ARLOCK = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARLOCK;

assign m_axi_gmem_0_ARPROT = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARPROT;

assign m_axi_gmem_0_ARQOS = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARQOS;

assign m_axi_gmem_0_ARREGION = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARREGION;

assign m_axi_gmem_0_ARSIZE = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARSIZE;

assign m_axi_gmem_0_ARUSER = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARUSER;

assign m_axi_gmem_0_ARVALID = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_ARVALID;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_RREADY = DMA24b_mm2s_fetch_U0_m_axi_gmem_0_RREADY;

assign m_axi_gmem_0_WDATA = 128'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 16'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign start_for_DMA24b_mm2s_streamout_U0_din = 1'b1;

endmodule //DMA24bUnit_mm2s_DMA24b_mm2s
