// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module DMA24bUnit_mm2s_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        STR_video_out_TREADY,
        mm_fifo_dout,
        mm_fifo_empty_n,
        mm_fifo_read,
        mm_fifo_num_data_valid,
        mm_fifo_fifo_cap,
        last_i,
        bound,
        STR_video_out_TDATA,
        STR_video_out_TVALID,
        STR_video_out_TKEEP,
        STR_video_out_TSTRB,
        STR_video_out_TUSER,
        STR_video_out_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 16'd1;
parameter    ap_ST_fsm_pp0_stage1 = 16'd2;
parameter    ap_ST_fsm_pp0_stage2 = 16'd4;
parameter    ap_ST_fsm_pp0_stage3 = 16'd8;
parameter    ap_ST_fsm_pp0_stage4 = 16'd16;
parameter    ap_ST_fsm_pp0_stage5 = 16'd32;
parameter    ap_ST_fsm_pp0_stage6 = 16'd64;
parameter    ap_ST_fsm_pp0_stage7 = 16'd128;
parameter    ap_ST_fsm_pp0_stage8 = 16'd256;
parameter    ap_ST_fsm_pp0_stage9 = 16'd512;
parameter    ap_ST_fsm_pp0_stage10 = 16'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 16'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 16'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 16'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 16'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   STR_video_out_TREADY;
input  [127:0] mm_fifo_dout;
input   mm_fifo_empty_n;
output   mm_fifo_read;
input  [8:0] mm_fifo_num_data_valid;
input  [8:0] mm_fifo_fifo_cap;
input  [8:0] last_i;
input  [19:0] bound;
output  [23:0] STR_video_out_TDATA;
output   STR_video_out_TVALID;
output  [2:0] STR_video_out_TKEEP;
output  [2:0] STR_video_out_TSTRB;
output  [0:0] STR_video_out_TUSER;
output  [0:0] STR_video_out_TLAST;

reg ap_idle;
reg mm_fifo_read;
reg[23:0] STR_video_out_TDATA;
reg STR_video_out_TVALID;
reg[0:0] STR_video_out_TUSER;
reg[0:0] STR_video_out_TLAST;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln38_fu_433_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage15;
reg   [0:0] icmp_ln38_reg_758;
reg    ap_block_state16_pp0_stage15_iter0_grp14;
reg    ap_block_pp0_stage15_subdone;
reg    mm_fifo_blk_n;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp1;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_grp6;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_grp11;
reg    STR_video_out_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp2;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp3;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_grp4;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_grp5;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_grp7;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_grp8;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_grp9;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_grp10;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_grp12;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14_grp13;
wire    ap_block_pp0_stage15_grp14;
wire    ap_block_pp0_stage0_grp15;
wire    ap_block_pp0_stage1_grp16;
reg   [7:0] reg_347;
reg    ap_block_state3_pp0_stage2_iter0_grp1;
reg    ap_block_pp0_stage2_11001_grp1;
reg    ap_block_state8_pp0_stage7_iter0_grp6;
reg    ap_block_pp0_stage7_11001_grp6;
reg    ap_block_state13_pp0_stage12_iter0_grp11;
reg    ap_block_pp0_stage12_11001_grp11;
reg   [7:0] reg_351;
reg   [7:0] reg_355;
reg   [7:0] reg_359;
reg   [7:0] reg_363;
reg   [7:0] reg_367;
reg   [7:0] reg_371;
reg   [7:0] reg_375;
reg   [7:0] reg_379;
reg   [7:0] reg_383;
reg   [7:0] reg_387;
reg   [7:0] reg_391;
reg   [7:0] reg_395;
wire   [7:0] grp_fu_207_p4;
reg   [7:0] reg_399;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
reg   [7:0] i_2_reg_747;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [0:0] icmp_ln39_fu_428_p2;
reg   [0:0] icmp_ln39_reg_752;
reg    ap_block_pp0_stage1_11001;
wire   [19:0] add_ln38_fu_438_p2;
reg   [19:0] add_ln38_reg_762;
reg   [11:0] j_load_reg_767;
wire   [11:0] add_ln38_1_fu_447_p2;
reg   [11:0] add_ln38_1_reg_772;
wire   [0:0] video_elt_out_last_fu_472_p2;
reg   [0:0] video_elt_out_last_reg_777;
wire   [7:0] grp_fu_197_p4;
reg   [7:0] tmp_31_reg_782;
reg   [7:0] i_fu_144;
wire   [7:0] i_3_fu_523_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1_grp0;
reg   [11:0] j_fu_148;
wire   [11:0] select_ln38_1_fu_463_p3;
reg   [19:0] indvar_flatten_fu_152;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage1;
wire   [23:0] video_elt_out_data_fu_481_p4;
reg    ap_block_pp0_stage2_01001_grp1;
wire   [23:0] video_elt_out_data_1_fu_543_p4;
reg    ap_block_state4_pp0_stage3_iter0_grp2;
reg    ap_block_pp0_stage3_01001_grp2;
wire   [23:0] video_elt_out_data_2_fu_554_p4;
reg    ap_block_state5_pp0_stage4_iter0_grp3;
reg    ap_block_pp0_stage4_01001_grp3;
wire   [23:0] video_elt_out_data_3_fu_565_p4;
reg    ap_block_state6_pp0_stage5_iter0_grp4;
reg    ap_block_pp0_stage5_01001_grp4;
wire   [23:0] video_elt_out_data_4_fu_576_p4;
reg    ap_block_state7_pp0_stage6_iter0_grp5;
reg    ap_block_pp0_stage6_01001_grp5;
wire   [23:0] video_elt_out_data_5_fu_591_p4;
reg    ap_block_pp0_stage7_01001_grp6;
wire   [23:0] video_elt_out_data_6_fu_602_p4;
reg    ap_block_state9_pp0_stage8_iter0_grp7;
reg    ap_block_pp0_stage8_01001_grp7;
wire   [23:0] video_elt_out_data_7_fu_613_p4;
reg    ap_block_state10_pp0_stage9_iter0_grp8;
reg    ap_block_pp0_stage9_01001_grp8;
wire   [23:0] video_elt_out_data_8_fu_624_p4;
reg    ap_block_state11_pp0_stage10_iter0_grp9;
reg    ap_block_pp0_stage10_01001_grp9;
wire   [23:0] video_elt_out_data_9_fu_635_p4;
reg    ap_block_state12_pp0_stage11_iter0_grp10;
reg    ap_block_pp0_stage11_01001_grp10;
wire   [23:0] video_elt_out_data_10_fu_650_p4;
reg    ap_block_pp0_stage12_01001_grp11;
wire   [23:0] video_elt_out_data_11_fu_661_p4;
reg    ap_block_state14_pp0_stage13_iter0_grp12;
reg    ap_block_pp0_stage13_01001_grp12;
wire   [23:0] video_elt_out_data_12_fu_671_p4;
reg    ap_block_state15_pp0_stage14_iter0_grp13;
reg    ap_block_pp0_stage14_01001_grp13;
wire   [23:0] video_elt_out_data_13_fu_682_p4;
reg    ap_block_pp0_stage15_01001_grp14;
wire   [23:0] video_elt_out_data_14_fu_693_p4;
reg    ap_block_state17_pp0_stage0_iter1_grp15;
reg    ap_block_pp0_stage0_01001_grp15;
wire   [23:0] video_elt_out_data_15_fu_704_p4;
reg    ap_block_pp0_stage1_01001_grp16;
wire   [0:0] video_elt_out_user_fu_516_p2;
reg    ap_block_pp0_stage3_11001_grp2;
reg    ap_block_pp0_stage4_11001_grp3;
reg    ap_block_pp0_stage5_11001_grp4;
reg    ap_block_pp0_stage6_11001_grp5;
reg    ap_block_pp0_stage8_11001_grp7;
reg    ap_block_pp0_stage9_11001_grp8;
reg    ap_block_pp0_stage10_11001_grp9;
reg    ap_block_pp0_stage11_11001_grp10;
reg    ap_block_pp0_stage13_11001_grp12;
reg    ap_block_pp0_stage14_11001_grp13;
reg    ap_block_pp0_stage15_11001_grp14;
reg    ap_block_pp0_stage0_11001_grp15;
reg    ap_block_pp0_stage1_11001_grp16;
wire   [8:0] zext_ln39_fu_424_p1;
wire   [7:0] select_ln38_fu_453_p3;
wire   [8:0] zext_ln38_fu_459_p1;
wire   [7:0] trunc_ln60_fu_477_p1;
wire   [7:0] trunc_ln51_fu_468_p1;
wire   [3:0] tmp_15_fu_498_p4;
wire   [7:0] or_ln51_fu_492_p2;
wire   [11:0] or_ln_fu_508_p3;
wire   [7:0] trunc_ln61_fu_587_p1;
wire   [7:0] trunc_ln62_fu_646_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [15:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
reg    ap_block_pp0_stage8_subdone;
reg    ap_block_pp0_stage9_subdone;
reg    ap_block_pp0_stage10_subdone;
reg    ap_block_pp0_stage11_subdone;
reg    ap_block_pp0_stage12_subdone;
reg    ap_block_pp0_stage13_subdone;
reg    ap_block_pp0_stage14_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 i_fu_144 = 8'd0;
#0 j_fu_148 = 12'd0;
#0 indvar_flatten_fu_152 = 20'd0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

DMA24bUnit_mm2s_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_144 <= 8'd0;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        i_fu_144 <= i_3_fu_523_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_152 <= 20'd0;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten_fu_152 <= add_ln38_reg_762;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_148 <= 12'd0;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        j_fu_148 <= select_ln38_1_fu_463_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln38_1_reg_772 <= add_ln38_1_fu_447_p2;
        i_2_reg_747 <= i_fu_144;
        icmp_ln39_reg_752 <= icmp_ln39_fu_428_p2;
        j_load_reg_767 <= j_fu_148;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln38_reg_762 <= add_ln38_fu_438_p2;
        icmp_ln38_reg_758 <= icmp_ln38_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_347 <= {{mm_fifo_dout[31:24]}};
        reg_351 <= {{mm_fifo_dout[39:32]}};
        reg_355 <= {{mm_fifo_dout[47:40]}};
        reg_359 <= {{mm_fifo_dout[55:48]}};
        reg_363 <= {{mm_fifo_dout[63:56]}};
        reg_367 <= {{mm_fifo_dout[71:64]}};
        reg_371 <= {{mm_fifo_dout[79:72]}};
        reg_375 <= {{mm_fifo_dout[87:80]}};
        reg_379 <= {{mm_fifo_dout[95:88]}};
        reg_383 <= {{mm_fifo_dout[103:96]}};
        reg_387 <= {{mm_fifo_dout[111:104]}};
        reg_391 <= {{mm_fifo_dout[119:112]}};
        reg_395 <= {{mm_fifo_dout[127:120]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        reg_399 <= {{mm_fifo_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        tmp_31_reg_782 <= {{mm_fifo_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        video_elt_out_last_reg_777 <= video_elt_out_last_fu_472_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        STR_video_out_TDATA = video_elt_out_data_15_fu_704_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        STR_video_out_TDATA = video_elt_out_data_14_fu_693_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_01001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        STR_video_out_TDATA = video_elt_out_data_13_fu_682_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_01001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        STR_video_out_TDATA = video_elt_out_data_12_fu_671_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_01001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        STR_video_out_TDATA = video_elt_out_data_11_fu_661_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_01001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        STR_video_out_TDATA = video_elt_out_data_10_fu_650_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_01001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        STR_video_out_TDATA = video_elt_out_data_9_fu_635_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_01001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        STR_video_out_TDATA = video_elt_out_data_8_fu_624_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_01001_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        STR_video_out_TDATA = video_elt_out_data_7_fu_613_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_01001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        STR_video_out_TDATA = video_elt_out_data_6_fu_602_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_01001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        STR_video_out_TDATA = video_elt_out_data_5_fu_591_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_01001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        STR_video_out_TDATA = video_elt_out_data_4_fu_576_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_01001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        STR_video_out_TDATA = video_elt_out_data_3_fu_565_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_01001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        STR_video_out_TDATA = video_elt_out_data_2_fu_554_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        STR_video_out_TDATA = video_elt_out_data_1_fu_543_p4;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        STR_video_out_TDATA = video_elt_out_data_fu_481_p4;
    end else begin
        STR_video_out_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln38_reg_758 
    == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp15) 
    & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        STR_video_out_TDATA_blk_n = STR_video_out_TREADY;
    end else begin
        STR_video_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        STR_video_out_TLAST = video_elt_out_last_reg_777;
    end else if ((((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_01001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_01001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_01001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_01001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_01001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_01001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_01001_grp8) & (1'b1 
    == ap_CS_fsm_pp0_stage9)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_01001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_01001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_01001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_01001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_01001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp1) 
    & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        STR_video_out_TLAST = 1'd0;
    end else begin
        STR_video_out_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_01001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_01001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_01001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_01001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_01001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_01001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_01001_grp8) & (1'b1 
    == ap_CS_fsm_pp0_stage9)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_01001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_01001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_01001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_01001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_01001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) 
    & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_01001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        STR_video_out_TUSER = 1'd0;
    end else if (((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        STR_video_out_TUSER = video_elt_out_user_fu_516_p2;
    end else begin
        STR_video_out_TUSER = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln38_reg_758 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9)) 
    | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) 
    | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        STR_video_out_TVALID = 1'b1;
    end else begin
        STR_video_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_433_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        mm_fifo_blk_n = mm_fifo_empty_n;
    end else begin
        mm_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln38_reg_758 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        mm_fifo_read = 1'b1;
    end else begin
        mm_fifo_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign STR_video_out_TKEEP = 3'd7;

assign STR_video_out_TSTRB = 3'd7;

assign add_ln38_1_fu_447_p2 = (j_fu_148 + 12'd1);

assign add_ln38_fu_438_p2 = (indvar_flatten_fu_152 + 20'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp15 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter1_grp15));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp15 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter1_grp15));
end

assign ap_block_pp0_stage0_grp15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter1_grp15));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_01001_grp9 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state11_pp0_stage10_iter0_grp9));
end

always @ (*) begin
    ap_block_pp0_stage10_11001_grp9 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state11_pp0_stage10_iter0_grp9));
end

assign ap_block_pp0_stage10_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state11_pp0_stage10_iter0_grp9));
end

always @ (*) begin
    ap_block_pp0_stage11_01001_grp10 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp10));
end

always @ (*) begin
    ap_block_pp0_stage11_11001_grp10 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp10));
end

assign ap_block_pp0_stage11_grp10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage11_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp10));
end

always @ (*) begin
    ap_block_pp0_stage12_01001_grp11 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state13_pp0_stage12_iter0_grp11));
end

always @ (*) begin
    ap_block_pp0_stage12_11001_grp11 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state13_pp0_stage12_iter0_grp11));
end

assign ap_block_pp0_stage12_grp11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage12_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state13_pp0_stage12_iter0_grp11));
end

always @ (*) begin
    ap_block_pp0_stage13_01001_grp12 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state14_pp0_stage13_iter0_grp12));
end

always @ (*) begin
    ap_block_pp0_stage13_11001_grp12 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state14_pp0_stage13_iter0_grp12));
end

assign ap_block_pp0_stage13_grp12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage13_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state14_pp0_stage13_iter0_grp12));
end

always @ (*) begin
    ap_block_pp0_stage14_01001_grp13 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state15_pp0_stage14_iter0_grp13));
end

always @ (*) begin
    ap_block_pp0_stage14_11001_grp13 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state15_pp0_stage14_iter0_grp13));
end

assign ap_block_pp0_stage14_grp13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage14_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state15_pp0_stage14_iter0_grp13));
end

always @ (*) begin
    ap_block_pp0_stage15_01001_grp14 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state16_pp0_stage15_iter0_grp14));
end

always @ (*) begin
    ap_block_pp0_stage15_11001_grp14 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state16_pp0_stage15_iter0_grp14));
end

assign ap_block_pp0_stage15_grp14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage15_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state16_pp0_stage15_iter0_grp14));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == STR_video_out_TREADY));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == STR_video_out_TREADY));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp16 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == STR_video_out_TREADY));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

assign ap_block_pp0_stage2_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp2));
end

assign ap_block_pp0_stage3_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage4_01001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp3));
end

assign ap_block_pp0_stage4_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage5_01001_grp4 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp4));
end

always @ (*) begin
    ap_block_pp0_stage5_11001_grp4 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp4));
end

assign ap_block_pp0_stage5_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp4));
end

always @ (*) begin
    ap_block_pp0_stage6_01001_grp5 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp5));
end

always @ (*) begin
    ap_block_pp0_stage6_11001_grp5 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp5));
end

assign ap_block_pp0_stage6_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp5));
end

always @ (*) begin
    ap_block_pp0_stage7_01001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp6));
end

always @ (*) begin
    ap_block_pp0_stage7_11001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp6));
end

assign ap_block_pp0_stage7_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp6));
end

always @ (*) begin
    ap_block_pp0_stage8_01001_grp7 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state9_pp0_stage8_iter0_grp7));
end

always @ (*) begin
    ap_block_pp0_stage8_11001_grp7 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state9_pp0_stage8_iter0_grp7));
end

assign ap_block_pp0_stage8_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state9_pp0_stage8_iter0_grp7));
end

always @ (*) begin
    ap_block_pp0_stage9_01001_grp8 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0_grp8));
end

always @ (*) begin
    ap_block_pp0_stage9_11001_grp8 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0_grp8));
end

assign ap_block_pp0_stage9_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage9_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0_grp8));
end

always @ (*) begin
    ap_block_state10_pp0_stage9_iter0_grp8 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state11_pp0_stage10_iter0_grp9 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state12_pp0_stage11_iter0_grp10 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state13_pp0_stage12_iter0_grp11 = (((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY)) | ((icmp_ln38_reg_758 == 1'd0) & (mm_fifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state14_pp0_stage13_iter0_grp12 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state15_pp0_stage14_iter0_grp13 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state16_pp0_stage15_iter0_grp14 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter1_grp15 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp1 = (((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY)) | ((icmp_ln38_reg_758 == 1'd0) & (mm_fifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp2 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp3 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0_grp4 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0_grp5 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0_grp6 = (((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY)) | ((icmp_ln38_reg_758 == 1'd0) & (mm_fifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state9_pp0_stage8_iter0_grp7 = ((icmp_ln38_reg_758 == 1'd0) & (1'b0 == STR_video_out_TREADY));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign grp_fu_197_p4 = {{mm_fifo_dout[15:8]}};

assign grp_fu_207_p4 = {{mm_fifo_dout[23:16]}};

assign i_3_fu_523_p2 = (select_ln38_fu_453_p3 + 8'd1);

assign icmp_ln38_fu_433_p2 = ((indvar_flatten_fu_152 == bound) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_428_p2 = (($signed(zext_ln39_fu_424_p1) > $signed(last_i)) ? 1'b1 : 1'b0);

assign or_ln51_fu_492_p2 = (trunc_ln51_fu_468_p1 | select_ln38_fu_453_p3);

assign or_ln_fu_508_p3 = {{tmp_15_fu_498_p4}, {or_ln51_fu_492_p2}};

assign select_ln38_1_fu_463_p3 = ((icmp_ln39_reg_752[0:0] == 1'b1) ? add_ln38_1_reg_772 : j_load_reg_767);

assign select_ln38_fu_453_p3 = ((icmp_ln39_reg_752[0:0] == 1'b1) ? 8'd0 : i_2_reg_747);

assign tmp_15_fu_498_p4 = {{select_ln38_1_fu_463_p3[11:8]}};

assign trunc_ln51_fu_468_p1 = select_ln38_1_fu_463_p3[7:0];

assign trunc_ln60_fu_477_p1 = mm_fifo_dout[7:0];

assign trunc_ln61_fu_587_p1 = mm_fifo_dout[7:0];

assign trunc_ln62_fu_646_p1 = mm_fifo_dout[7:0];

assign video_elt_out_data_10_fu_650_p4 = {{{reg_391}, {reg_395}}, {trunc_ln62_fu_646_p1}};

assign video_elt_out_data_11_fu_661_p4 = {{{tmp_31_reg_782}, {reg_399}}, {reg_347}};

assign video_elt_out_data_12_fu_671_p4 = {{{reg_351}, {reg_355}}, {reg_359}};

assign video_elt_out_data_13_fu_682_p4 = {{{reg_363}, {reg_367}}, {reg_371}};

assign video_elt_out_data_14_fu_693_p4 = {{{reg_375}, {reg_379}}, {reg_383}};

assign video_elt_out_data_15_fu_704_p4 = {{{reg_387}, {reg_391}}, {reg_395}};

assign video_elt_out_data_1_fu_543_p4 = {{{reg_347}, {reg_351}}, {reg_355}};

assign video_elt_out_data_2_fu_554_p4 = {{{reg_359}, {reg_363}}, {reg_367}};

assign video_elt_out_data_3_fu_565_p4 = {{{reg_371}, {reg_375}}, {reg_379}};

assign video_elt_out_data_4_fu_576_p4 = {{{reg_383}, {reg_387}}, {reg_391}};

assign video_elt_out_data_5_fu_591_p4 = {{{reg_395}, {trunc_ln61_fu_587_p1}}, {grp_fu_197_p4}};

assign video_elt_out_data_6_fu_602_p4 = {{{reg_399}, {reg_347}}, {reg_351}};

assign video_elt_out_data_7_fu_613_p4 = {{{reg_355}, {reg_359}}, {reg_363}};

assign video_elt_out_data_8_fu_624_p4 = {{{reg_367}, {reg_371}}, {reg_375}};

assign video_elt_out_data_9_fu_635_p4 = {{{reg_379}, {reg_383}}, {reg_387}};

assign video_elt_out_data_fu_481_p4 = {{{trunc_ln60_fu_477_p1}, {grp_fu_197_p4}}, {grp_fu_207_p4}};

assign video_elt_out_last_fu_472_p2 = ((zext_ln38_fu_459_p1 == last_i) ? 1'b1 : 1'b0);

assign video_elt_out_user_fu_516_p2 = ((or_ln_fu_508_p3 == 12'd0) ? 1'b1 : 1'b0);

assign zext_ln38_fu_459_p1 = select_ln38_fu_453_p3;

assign zext_ln39_fu_424_p1 = i_fu_144;

endmodule //DMA24bUnit_mm2s_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop
