set_property SRC_FILE_INFO {cfile:/home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/Architectures/DMA_TPG_AXISelect/Cora-Z7-07-Master-ILA.xdc rfile:../../../Cora-Z7-07-Master-ILA.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports CLK_I]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports reset]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports chanel_select]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {VGA_R[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {VGA_R[1]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {VGA_R[2]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {VGA_R[3]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {VGA_B[0]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {VGA_B[1]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {VGA_B[2]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {VGA_B[3]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {VGA_G[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {VGA_G[1]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {VGA_G[2]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {VGA_G[3]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports VGA_HS_O]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports VGA_VS_O]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0_clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/ControleurVGA_v3_0/VGA_G[0]} {design_1_i/ControleurVGA_v3_0/VGA_G[1]} {design_1_i/ControleurVGA_v3_0/VGA_G[2]} {design_1_i/ControleurVGA_v3_0/VGA_G[3]}]]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/ControleurVGA_v3_0/VGA_B[0]} {design_1_i/ControleurVGA_v3_0/VGA_B[1]} {design_1_i/ControleurVGA_v3_0/VGA_B[2]} {design_1_i/ControleurVGA_v3_0/VGA_B[3]}]]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/ControleurVGA_v3_0/VGA_R[0]} {design_1_i/ControleurVGA_v3_0/VGA_R[1]} {design_1_i/ControleurVGA_v3_0/VGA_R[2]} {design_1_i/ControleurVGA_v3_0/VGA_R[3]}]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/AXI_Select_0/tdata_b[0]} {design_1_i/AXI_Select_0/tdata_b[1]} {design_1_i/AXI_Select_0/tdata_b[2]} {design_1_i/AXI_Select_0/tdata_b[3]} {design_1_i/AXI_Select_0/tdata_b[4]} {design_1_i/AXI_Select_0/tdata_b[5]} {design_1_i/AXI_Select_0/tdata_b[6]} {design_1_i/AXI_Select_0/tdata_b[7]} {design_1_i/AXI_Select_0/tdata_b[8]} {design_1_i/AXI_Select_0/tdata_b[9]} {design_1_i/AXI_Select_0/tdata_b[10]} {design_1_i/AXI_Select_0/tdata_b[11]} {design_1_i/AXI_Select_0/tdata_b[12]} {design_1_i/AXI_Select_0/tdata_b[13]} {design_1_i/AXI_Select_0/tdata_b[14]} {design_1_i/AXI_Select_0/tdata_b[15]} {design_1_i/AXI_Select_0/tdata_b[16]} {design_1_i/AXI_Select_0/tdata_b[17]} {design_1_i/AXI_Select_0/tdata_b[18]} {design_1_i/AXI_Select_0/tdata_b[19]} {design_1_i/AXI_Select_0/tdata_b[20]} {design_1_i/AXI_Select_0/tdata_b[21]} {design_1_i/AXI_Select_0/tdata_b[22]} {design_1_i/AXI_Select_0/tdata_b[23]}]]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/AXI_Select_0/tdata_out[0]} {design_1_i/AXI_Select_0/tdata_out[1]} {design_1_i/AXI_Select_0/tdata_out[2]} {design_1_i/AXI_Select_0/tdata_out[3]} {design_1_i/AXI_Select_0/tdata_out[4]} {design_1_i/AXI_Select_0/tdata_out[5]} {design_1_i/AXI_Select_0/tdata_out[6]} {design_1_i/AXI_Select_0/tdata_out[7]} {design_1_i/AXI_Select_0/tdata_out[8]} {design_1_i/AXI_Select_0/tdata_out[9]} {design_1_i/AXI_Select_0/tdata_out[10]} {design_1_i/AXI_Select_0/tdata_out[11]} {design_1_i/AXI_Select_0/tdata_out[12]} {design_1_i/AXI_Select_0/tdata_out[13]} {design_1_i/AXI_Select_0/tdata_out[14]} {design_1_i/AXI_Select_0/tdata_out[15]} {design_1_i/AXI_Select_0/tdata_out[16]} {design_1_i/AXI_Select_0/tdata_out[17]} {design_1_i/AXI_Select_0/tdata_out[18]} {design_1_i/AXI_Select_0/tdata_out[19]} {design_1_i/AXI_Select_0/tdata_out[20]} {design_1_i/AXI_Select_0/tdata_out[21]} {design_1_i/AXI_Select_0/tdata_out[22]} {design_1_i/AXI_Select_0/tdata_out[23]}]]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/AXI_Select_0/tdata_a[0]} {design_1_i/AXI_Select_0/tdata_a[1]} {design_1_i/AXI_Select_0/tdata_a[2]} {design_1_i/AXI_Select_0/tdata_a[3]} {design_1_i/AXI_Select_0/tdata_a[4]} {design_1_i/AXI_Select_0/tdata_a[5]} {design_1_i/AXI_Select_0/tdata_a[6]} {design_1_i/AXI_Select_0/tdata_a[7]} {design_1_i/AXI_Select_0/tdata_a[8]} {design_1_i/AXI_Select_0/tdata_a[9]} {design_1_i/AXI_Select_0/tdata_a[10]} {design_1_i/AXI_Select_0/tdata_a[11]} {design_1_i/AXI_Select_0/tdata_a[12]} {design_1_i/AXI_Select_0/tdata_a[13]} {design_1_i/AXI_Select_0/tdata_a[14]} {design_1_i/AXI_Select_0/tdata_a[15]} {design_1_i/AXI_Select_0/tdata_a[16]} {design_1_i/AXI_Select_0/tdata_a[17]} {design_1_i/AXI_Select_0/tdata_a[18]} {design_1_i/AXI_Select_0/tdata_a[19]} {design_1_i/AXI_Select_0/tdata_a[20]} {design_1_i/AXI_Select_0/tdata_a[21]} {design_1_i/AXI_Select_0/tdata_a[22]} {design_1_i/AXI_Select_0/tdata_a[23]}]]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/AXI_Select_0/chanel_select]]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/ControleurVGA_v3_0/tready]]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
