#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 01 17:03:20 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 6b2597bbdbe249a6bd7b8f0dd3bce309 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RGBtoGray_tb_behav xil_defaultlib.RGBtoGray_tb -log elaborate.log"
xelab -wto 6b2597bbdbe249a6bd7b8f0dd3bce309 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RGBtoGray_tb_behav xil_defaultlib.RGBtoGray_tb -log elaborate.log

