#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 02 15:08:51 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim RGBtoGray_tb_behav -key {Behavioral:sim_1:Functional:RGBtoGray_tb} -tclbatch RGBtoGray_tb.tcl -view /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/IP/RGBtoGray/RGBtoGray.sim/RGBtoGray_tb_behav.wcfg -log simulate.log"
xsim RGBtoGray_tb_behav -key {Behavioral:sim_1:Functional:RGBtoGray_tb} -tclbatch RGBtoGray_tb.tcl -view /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/IP/RGBtoGray/RGBtoGray.sim/RGBtoGray_tb_behav.wcfg -log simulate.log

