#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Sep 17 10:04:03 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto d5810d5df2484fdabc0082c292827a19 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot clk_wiz_tb_behav xil_defaultlib.clk_wiz_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto d5810d5df2484fdabc0082c292827a19 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot clk_wiz_tb_behav xil_defaultlib.clk_wiz_tb xil_defaultlib.glbl -log elaborate.log

