#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Sep 17 10:46:50 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 2a5f7629a60d4840b217fa00e31aa774 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot counter_tb_behav xil_defaultlib.counter_tb -log elaborate.log"
xelab -wto 2a5f7629a60d4840b217fa00e31aa774 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot counter_tb_behav xil_defaultlib.counter_tb -log elaborate.log

