#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 04 18:02:29 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 7ad0c694514749c4acecbfb885fb0e7d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot AXI4_stream_Slave_tb_behav xil_defaultlib.AXI4_stream_Slave_tb -log elaborate.log"
xelab -wto 7ad0c694514749c4acecbfb885fb0e7d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot AXI4_stream_Slave_tb_behav xil_defaultlib.AXI4_stream_Slave_tb -log elaborate.log

