// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module DMA24bUnit_mm2s_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        mm_fifo_din,
        mm_fifo_full_n,
        mm_fifo_write,
        mm_fifo_num_data_valid,
        mm_fifo_fifo_cap,
        bound4,
        p_cast,
        bound,
        mm_buffer
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [127:0] m_axi_gmem_0_WDATA;
output  [15:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [127:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [10:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
output  [127:0] mm_fifo_din;
input   mm_fifo_full_n;
output   mm_fifo_write;
input  [8:0] mm_fifo_num_data_valid;
input  [8:0] mm_fifo_fifo_cap;
input  [21:0] bound4;
input  [9:0] p_cast;
input  [9:0] bound;
input  [63:0] mm_buffer;

reg ap_idle;
reg m_axi_gmem_0_ARVALID;
reg m_axi_gmem_0_RREADY;
reg mm_fifo_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg   [0:0] or_ln15_reg_459;
reg   [0:0] or_ln15_1_reg_463;
reg    ap_predicate_op77_readreq_state4;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln14_reg_442;
reg   [0:0] icmp_ln14_reg_442_pp0_iter10_reg;
reg    ap_block_state12_pp0_stage0_iter11;
reg   [0:0] icmp_ln14_reg_442_pp0_iter11_reg;
reg    ap_block_state13_pp0_stage0_iter12;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln14_fu_207_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mm_fifo_blk_n;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_R;
reg    gmem_blk_n_AR;
reg   [0:0] first_iter_1_reg_152;
reg   [0:0] first_iter_0_reg_163;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] bound_cast_fu_176_p1;
reg   [10:0] bound_cast_reg_432;
wire   [63:0] p_cast_cast_fu_180_p1;
reg   [63:0] p_cast_cast_reg_437;
reg   [0:0] icmp_ln14_reg_442_pp0_iter1_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter2_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter3_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter4_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter5_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter6_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter7_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter8_reg;
reg   [0:0] icmp_ln14_reg_442_pp0_iter9_reg;
wire   [0:0] icmp_ln15_fu_230_p2;
reg   [0:0] icmp_ln15_reg_446;
wire   [22:0] empty_54_fu_269_p2;
reg   [22:0] empty_54_reg_454;
wire   [0:0] or_ln15_fu_324_p2;
wire   [0:0] or_ln15_1_fu_342_p2;
reg   [59:0] trunc_ln1_reg_468;
reg   [127:0] data_mm_buffer_reg_479;
reg    ap_condition_exit_pp0_iter2_stage0;
reg   [0:0] ap_phi_mux_first_iter_1_phi_fu_156_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_168_p4;
wire  signed [63:0] sext_ln15_fu_389_p1;
reg   [5:0] b_fu_94;
wire   [5:0] select_ln16_fu_376_p3;
reg   [10:0] indvar_flatten_fu_98;
wire   [10:0] select_ln15_fu_281_p3;
reg   [11:0] j_fu_102;
wire   [11:0] select_ln14_fu_241_p3;
reg   [21:0] indvar_flatten12_fu_106;
wire   [21:0] add_ln14_fu_213_p2;
reg   [21:0] ap_sig_allocacmp_indvar_flatten12_load;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] add_ln14_1_fu_235_p2;
wire   [18:0] tmp_fu_257_p3;
wire   [22:0] p_shl_fu_249_p3;
wire   [22:0] p_shl9_fu_265_p1;
wire   [10:0] add_ln15_fu_275_p2;
wire   [0:0] icmp_ln16_fu_312_p2;
wire   [0:0] xor_ln14_fu_307_p2;
wire   [0:0] and_ln14_fu_318_p2;
wire   [0:0] or_ln14_fu_302_p2;
wire   [0:0] xor_ln15_fu_330_p2;
wire   [0:0] and_ln15_fu_336_p2;
wire   [63:0] p_cast3_fu_347_p1;
wire   [63:0] empty_55_fu_350_p2;
wire   [0:0] or_ln16_fu_371_p2;
wire   [5:0] add_ln16_fu_365_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 b_fu_94 = 6'd0;
#0 indvar_flatten_fu_98 = 11'd0;
#0 j_fu_102 = 12'd0;
#0 indvar_flatten12_fu_106 = 22'd0;
#0 ap_done_reg = 1'b0;
end

DMA24bUnit_mm2s_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            b_fu_94 <= 6'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln14_reg_442_pp0_iter1_reg == 1'd0))) begin
            b_fu_94 <= select_ln16_fu_376_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_442_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_163 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_163 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_442_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_1_reg_152 <= or_ln15_1_reg_463;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_1_reg_152 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln14_fu_207_p2 == 1'd0))) begin
            indvar_flatten12_fu_106 <= add_ln14_fu_213_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_106 <= 22'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_98 <= 11'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln14_reg_442 == 1'd0))) begin
            indvar_flatten_fu_98 <= select_ln15_fu_281_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_102 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln14_reg_442 == 1'd0))) begin
            j_fu_102 <= select_ln14_fu_241_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        data_mm_buffer_reg_479 <= m_axi_gmem_0_RDATA;
        icmp_ln14_reg_442_pp0_iter10_reg <= icmp_ln14_reg_442_pp0_iter9_reg;
        icmp_ln14_reg_442_pp0_iter11_reg <= icmp_ln14_reg_442_pp0_iter10_reg;
        icmp_ln14_reg_442_pp0_iter2_reg <= icmp_ln14_reg_442_pp0_iter1_reg;
        icmp_ln14_reg_442_pp0_iter3_reg <= icmp_ln14_reg_442_pp0_iter2_reg;
        icmp_ln14_reg_442_pp0_iter4_reg <= icmp_ln14_reg_442_pp0_iter3_reg;
        icmp_ln14_reg_442_pp0_iter5_reg <= icmp_ln14_reg_442_pp0_iter4_reg;
        icmp_ln14_reg_442_pp0_iter6_reg <= icmp_ln14_reg_442_pp0_iter5_reg;
        icmp_ln14_reg_442_pp0_iter7_reg <= icmp_ln14_reg_442_pp0_iter6_reg;
        icmp_ln14_reg_442_pp0_iter8_reg <= icmp_ln14_reg_442_pp0_iter7_reg;
        icmp_ln14_reg_442_pp0_iter9_reg <= icmp_ln14_reg_442_pp0_iter8_reg;
        or_ln15_reg_459 <= or_ln15_fu_324_p2;
        trunc_ln1_reg_468 <= {{empty_55_fu_350_p2[63:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        bound_cast_reg_432[9 : 0] <= bound_cast_fu_176_p1[9 : 0];
        empty_54_reg_454[22 : 7] <= empty_54_fu_269_p2[22 : 7];
        icmp_ln14_reg_442 <= icmp_ln14_fu_207_p2;
        icmp_ln14_reg_442_pp0_iter1_reg <= icmp_ln14_reg_442;
        icmp_ln15_reg_446 <= icmp_ln15_fu_230_p2;
        p_cast_cast_reg_437[9 : 0] <= p_cast_cast_fu_180_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln15_1_reg_463 <= or_ln15_1_fu_342_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln14_fu_207_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln14_reg_442_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_442_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_0_phi_fu_168_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_168_p4 = first_iter_0_reg_163;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_442_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_1_phi_fu_156_p4 = or_ln15_1_reg_463;
    end else begin
        ap_phi_mux_first_iter_1_phi_fu_156_p4 = first_iter_1_reg_152;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 22'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_106;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op77_readreq_state4 == 1'b1))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln14_reg_442_pp0_iter10_reg == 1'd0))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op77_readreq_state4 == 1'b1))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln14_reg_442_pp0_iter10_reg == 1'd0))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln14_reg_442_pp0_iter11_reg == 1'd0))) begin
        mm_fifo_blk_n = mm_fifo_full_n;
    end else begin
        mm_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln14_reg_442_pp0_iter11_reg == 1'd0))) begin
        mm_fifo_write = 1'b1;
    end else begin
        mm_fifo_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln14_1_fu_235_p2 = (j_fu_102 + 12'd1);

assign add_ln14_fu_213_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 22'd1);

assign add_ln15_fu_275_p2 = (indvar_flatten_fu_98 + 11'd1);

assign add_ln16_fu_365_p2 = (b_fu_94 + 6'd1);

assign and_ln14_fu_318_p2 = (xor_ln14_fu_307_p2 & icmp_ln16_fu_312_p2);

assign and_ln15_fu_336_p2 = (xor_ln15_fu_330_p2 & ap_phi_mux_first_iter_1_phi_fu_156_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = ((icmp_ln14_reg_442_pp0_iter10_reg == 1'd0) & (m_axi_gmem_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp0_stage0_iter12 = ((icmp_ln14_reg_442_pp0_iter11_reg == 1'd0) & (mm_fifo_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem_0_ARREADY == 1'b0) & (ap_predicate_op77_readreq_state4 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op77_readreq_state4 = ((or_ln15_1_reg_463 == 1'd1) & (or_ln15_reg_459 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign bound_cast_fu_176_p1 = bound;

assign empty_54_fu_269_p2 = (p_shl_fu_249_p3 - p_shl9_fu_265_p1);

assign empty_55_fu_350_p2 = (p_cast3_fu_347_p1 + mm_buffer);

assign icmp_ln14_fu_207_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == bound4) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_230_p2 = ((indvar_flatten_fu_98 == bound_cast_reg_432) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_312_p2 = ((b_fu_94 == 6'd40) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARADDR = sext_ln15_fu_389_p1;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = p_cast_cast_reg_437;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 128'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 16'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign mm_fifo_din = data_mm_buffer_reg_479;

assign or_ln14_fu_302_p2 = (icmp_ln15_reg_446 | ap_phi_mux_first_iter_0_phi_fu_168_p4);

assign or_ln15_1_fu_342_p2 = (icmp_ln15_reg_446 | and_ln15_fu_336_p2);

assign or_ln15_fu_324_p2 = (or_ln14_fu_302_p2 | and_ln14_fu_318_p2);

assign or_ln16_fu_371_p2 = (icmp_ln15_reg_446 | and_ln14_fu_318_p2);

assign p_cast3_fu_347_p1 = empty_54_reg_454;

assign p_cast_cast_fu_180_p1 = p_cast;

assign p_shl9_fu_265_p1 = tmp_fu_257_p3;

assign p_shl_fu_249_p3 = {{select_ln14_fu_241_p3}, {11'd0}};

assign select_ln14_fu_241_p3 = ((icmp_ln15_fu_230_p2[0:0] == 1'b1) ? add_ln14_1_fu_235_p2 : j_fu_102);

assign select_ln15_fu_281_p3 = ((icmp_ln15_fu_230_p2[0:0] == 1'b1) ? 11'd1 : add_ln15_fu_275_p2);

assign select_ln16_fu_376_p3 = ((or_ln16_fu_371_p2[0:0] == 1'b1) ? 6'd1 : add_ln16_fu_365_p2);

assign sext_ln15_fu_389_p1 = $signed(trunc_ln1_reg_468);

assign tmp_fu_257_p3 = {{select_ln14_fu_241_p3}, {7'd0}};

assign xor_ln14_fu_307_p2 = (icmp_ln15_reg_446 ^ 1'd1);

assign xor_ln15_fu_330_p2 = (icmp_ln16_fu_312_p2 ^ 1'd1);

always @ (posedge ap_clk) begin
    bound_cast_reg_432[10] <= 1'b0;
    p_cast_cast_reg_437[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    empty_54_reg_454[6:0] <= 7'b0000000;
end

endmodule //DMA24bUnit_mm2s_DMA24b_mm2s_fetch_Pipeline_line_loop_burst_loop_beat_loop
