// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module DMA24bUnit_mm2s_DMA24b_mm2s_streamout (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        STR_video_out_TDATA,
        STR_video_out_TVALID,
        STR_video_out_TREADY,
        STR_video_out_TKEEP,
        STR_video_out_TSTRB,
        STR_video_out_TUSER,
        STR_video_out_TLAST,
        mm_fifo_dout,
        mm_fifo_empty_n,
        mm_fifo_read,
        mm_fifo_num_data_valid,
        mm_fifo_fifo_cap,
        img_w_dout,
        img_w_empty_n,
        img_w_read,
        img_w_num_data_valid,
        img_w_fifo_cap,
        img_h_dout,
        img_h_empty_n,
        img_h_read,
        img_h_num_data_valid,
        img_h_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [23:0] STR_video_out_TDATA;
output   STR_video_out_TVALID;
input   STR_video_out_TREADY;
output  [2:0] STR_video_out_TKEEP;
output  [2:0] STR_video_out_TSTRB;
output  [0:0] STR_video_out_TUSER;
output  [0:0] STR_video_out_TLAST;
input  [127:0] mm_fifo_dout;
input   mm_fifo_empty_n;
output   mm_fifo_read;
input  [8:0] mm_fifo_num_data_valid;
input  [8:0] mm_fifo_fifo_cap;
input  [11:0] img_w_dout;
input   img_w_empty_n;
output   img_w_read;
input  [2:0] img_w_num_data_valid;
input  [2:0] img_w_fifo_cap;
input  [11:0] img_h_dout;
input   img_h_empty_n;
output   img_h_read;
input  [2:0] img_h_num_data_valid;
input  [2:0] img_h_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[23:0] STR_video_out_TDATA;
reg[2:0] STR_video_out_TKEEP;
reg[2:0] STR_video_out_TSTRB;
reg[0:0] STR_video_out_TUSER;
reg[0:0] STR_video_out_TLAST;
reg img_w_read;
reg img_h_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_w_blk_n;
reg    img_h_blk_n;
reg   [11:0] img_h_1_reg_145;
reg    ap_block_state1;
reg   [7:0] tmp_s_reg_150;
wire    ap_CS_fsm_state2;
wire   [8:0] last_i_fu_138_p2;
reg   [8:0] last_i_reg_166;
wire    ap_CS_fsm_state3;
wire   [19:0] grp_fu_106_p2;
reg   [19:0] bound_reg_171;
wire    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start;
wire    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done;
wire    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_idle;
wire    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_ready;
wire    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TREADY;
wire    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_mm_fifo_read;
wire   [23:0] grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA;
wire    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID;
wire   [2:0] grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP;
wire   [2:0] grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB;
wire   [0:0] grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER;
wire   [0:0] grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST;
reg    grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [23:0] STR_video_out_TDATA_reg;
reg   [2:0] STR_video_out_TKEEP_reg;
reg   [2:0] STR_video_out_TSTRB_reg;
reg   [0:0] STR_video_out_TUSER_reg;
reg   [0:0] STR_video_out_TLAST_reg;
wire   [11:0] grp_fu_106_p0;
wire   [7:0] grp_fu_106_p1;
wire   [8:0] zext_ln37_fu_135_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire   [19:0] grp_fu_106_p00;
wire   [19:0] grp_fu_106_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg = 1'b0;
end

DMA24bUnit_mm2s_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start),
    .ap_done(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done),
    .ap_idle(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_idle),
    .ap_ready(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_ready),
    .STR_video_out_TREADY(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TREADY),
    .mm_fifo_dout(mm_fifo_dout),
    .mm_fifo_empty_n(mm_fifo_empty_n),
    .mm_fifo_read(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_mm_fifo_read),
    .mm_fifo_num_data_valid(9'd0),
    .mm_fifo_fifo_cap(9'd0),
    .last_i(last_i_reg_166),
    .bound(bound_reg_171),
    .STR_video_out_TDATA(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA),
    .STR_video_out_TVALID(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID),
    .STR_video_out_TKEEP(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP),
    .STR_video_out_TSTRB(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB),
    .STR_video_out_TUSER(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER),
    .STR_video_out_TLAST(grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST)
);

DMA24bUnit_mm2s_mul_12ns_8ns_20_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 20 ))
mul_12ns_8ns_20_2_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_106_p0),
    .din1(grp_fu_106_p1),
    .ce(1'b1),
    .dout(grp_fu_106_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_ready == 1'b1)) begin
            grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID == 1'b1))) begin
        STR_video_out_TDATA_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA;
        STR_video_out_TKEEP_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP;
        STR_video_out_TLAST_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST;
        STR_video_out_TSTRB_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB;
        STR_video_out_TUSER_reg <= grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bound_reg_171 <= grp_fu_106_p2;
        last_i_reg_166 <= last_i_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        img_h_1_reg_145 <= img_h_dout;
        tmp_s_reg_150 <= {{img_w_dout[11:4]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID == 1'b1))) begin
        STR_video_out_TDATA = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TDATA;
    end else begin
        STR_video_out_TDATA = STR_video_out_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID == 1'b1))) begin
        STR_video_out_TKEEP = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TKEEP;
    end else begin
        STR_video_out_TKEEP = STR_video_out_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID == 1'b1))) begin
        STR_video_out_TLAST = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TLAST;
    end else begin
        STR_video_out_TLAST = STR_video_out_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID == 1'b1))) begin
        STR_video_out_TSTRB = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TSTRB;
    end else begin
        STR_video_out_TSTRB = STR_video_out_TSTRB_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID == 1'b1))) begin
        STR_video_out_TUSER = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TUSER;
    end else begin
        STR_video_out_TUSER = STR_video_out_TUSER_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_h_blk_n = img_h_empty_n;
    end else begin
        img_h_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        img_h_read = 1'b1;
    end else begin
        img_h_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_w_blk_n = img_w_empty_n;
    end else begin
        img_w_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        img_w_read = 1'b1;
    end else begin
        img_w_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign STR_video_out_TVALID = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TVALID;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (img_h_empty_n == 1'b0) | (img_w_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_STR_video_out_TREADY = (ap_CS_fsm_state4 & STR_video_out_TREADY);

assign grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_ap_start_reg;

assign grp_fu_106_p0 = grp_fu_106_p00;

assign grp_fu_106_p00 = img_h_1_reg_145;

assign grp_fu_106_p1 = grp_fu_106_p10;

assign grp_fu_106_p10 = tmp_s_reg_150;

assign last_i_fu_138_p2 = ($signed(zext_ln37_fu_135_p1) + $signed(9'd511));

assign mm_fifo_read = grp_DMA24b_mm2s_streamout_Pipeline_line_loop_group_loop_fu_72_mm_fifo_read;

assign zext_ln37_fu_135_p1 = tmp_s_reg_150;

endmodule //DMA24bUnit_mm2s_DMA24b_mm2s_streamout
