#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 25 17:31:44 CEST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Driver_VGA_tb_behav -key {Behavioral:sim_1:Functional:Driver_VGA_tb} -tclbatch Driver_VGA_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/Architectures/Driver_VGA/Driver_VGA.sim/Driver_VGA_tb_behav.wcfg -log simulate.log"
xsim Driver_VGA_tb_behav -key {Behavioral:sim_1:Functional:Driver_VGA_tb} -tclbatch Driver_VGA_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/glen/Documents/AJC-Expleo/Travaux/Projet_CronerDetection/Architectures/Driver_VGA/Driver_VGA.sim/Driver_VGA_tb_behav.wcfg -log simulate.log

